// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package notifications

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// NotificationsRequestBuilder builds and executes requests for operations under \notifications
type NotificationsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Announcements the announcements property
// returns a *AnnouncementsRequestBuilder when successful
func (m *NotificationsRequestBuilder) Announcements()(*AnnouncementsRequestBuilder) {
    return NewAnnouncementsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ById gets an item from the github.com/leadpingai/leadping-go.notifications.item collection
// returns a *NotificationsItemRequestBuilder when successful
func (m *NotificationsRequestBuilder) ById(id string)(*NotificationsItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if id != "" {
        urlTplParams["id"] = id
    }
    return NewNotificationsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewNotificationsRequestBuilderInternal instantiates a new NotificationsRequestBuilder and sets the default values.
func NewNotificationsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*NotificationsRequestBuilder) {
    m := &NotificationsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/notifications", pathParameters),
    }
    return m
}
// NewNotificationsRequestBuilder instantiates a new NotificationsRequestBuilder and sets the default values.
func NewNotificationsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*NotificationsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewNotificationsRequestBuilderInternal(urlParams, requestAdapter)
}
// MarkAllRead the markAllRead property
// returns a *MarkAllReadRequestBuilder when successful
func (m *NotificationsRequestBuilder) MarkAllRead()(*MarkAllReadRequestBuilder) {
    return NewMarkAllReadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Me the me property
// returns a *MeRequestBuilder when successful
func (m *NotificationsRequestBuilder) Me()(*MeRequestBuilder) {
    return NewMeRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// UnreadCount the unreadCount property
// returns a *UnreadCountRequestBuilder when successful
func (m *NotificationsRequestBuilder) UnreadCount()(*UnreadCountRequestBuilder) {
    return NewUnreadCountRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
