// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package businesses

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ApiKeysRequestBuilder builds and executes requests for operations under \businesses\api-keys
type ApiKeysRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewApiKeysRequestBuilderInternal instantiates a new ApiKeysRequestBuilder and sets the default values.
func NewApiKeysRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiKeysRequestBuilder) {
    m := &ApiKeysRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/businesses/api-keys", pathParameters),
    }
    return m
}
// NewApiKeysRequestBuilder instantiates a new ApiKeysRequestBuilder and sets the default values.
func NewApiKeysRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiKeysRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewApiKeysRequestBuilderInternal(urlParams, requestAdapter)
}
// My the my property
// returns a *ApiKeysMyRequestBuilder when successful
func (m *ApiKeysRequestBuilder) My()(*ApiKeysMyRequestBuilder) {
    return NewApiKeysMyRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
