// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type BlogSocialPlatform int

const (
	FACEBOOK_BLOGSOCIALPLATFORM BlogSocialPlatform = iota
	INSTAGRAM_BLOGSOCIALPLATFORM
	X_BLOGSOCIALPLATFORM
	LINKEDIN_BLOGSOCIALPLATFORM
)

func (i BlogSocialPlatform) String() string {
	return []string{"facebook", "instagram", "x", "linkedin"}[i]
}

func ParseBlogSocialPlatform(v string) (any, error) {
	result := FACEBOOK_BLOGSOCIALPLATFORM
	switch v {
	case "facebook":
		result = FACEBOOK_BLOGSOCIALPLATFORM
	case "instagram":
		result = INSTAGRAM_BLOGSOCIALPLATFORM
	case "x":
		result = X_BLOGSOCIALPLATFORM
	case "linkedin":
		result = LINKEDIN_BLOGSOCIALPLATFORM
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeBlogSocialPlatform(values []BlogSocialPlatform) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i BlogSocialPlatform) isMultiValue() bool {
	return false
}
