// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the supported Billing Plan values.
type BusinessRequest_billingPlan int

const (
    ANNUAL_BUSINESSREQUEST_BILLINGPLAN BusinessRequest_billingPlan = iota
    MONTHLY_BUSINESSREQUEST_BILLINGPLAN
)

func (i BusinessRequest_billingPlan) String() string {
    return []string{"Annual", "Monthly"}[i]
}
func ParseBusinessRequest_billingPlan(v string) (any, error) {
    result := ANNUAL_BUSINESSREQUEST_BILLINGPLAN
    switch v {
        case "Annual":
            result = ANNUAL_BUSINESSREQUEST_BILLINGPLAN
        case "Monthly":
            result = MONTHLY_BUSINESSREQUEST_BILLINGPLAN
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeBusinessRequest_billingPlan(values []BusinessRequest_billingPlan) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i BusinessRequest_billingPlan) isMultiValue() bool {
    return false
}
