// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// BusinessResponse_compliancePolicy the compliance policy value for this business.
type BusinessResponse_compliancePolicy struct {
    BusinessCompliancePolicy
}
// NewBusinessResponse_compliancePolicy instantiates a new BusinessResponse_compliancePolicy and sets the default values.
func NewBusinessResponse_compliancePolicy()(*BusinessResponse_compliancePolicy) {
    m := &BusinessResponse_compliancePolicy{
        BusinessCompliancePolicy: *NewBusinessCompliancePolicy(),
    }
    return m
}
// CreateBusinessResponse_compliancePolicyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBusinessResponse_compliancePolicyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBusinessResponse_compliancePolicy(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BusinessResponse_compliancePolicy) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.BusinessCompliancePolicy.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *BusinessResponse_compliancePolicy) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.BusinessCompliancePolicy.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type BusinessResponse_compliancePolicyable interface {
    BusinessCompliancePolicyable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
