// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// BusinessUserRequest request payload for business user.
type BusinessUserRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The email address associated with this business user.
    email *string
    // The role value for this business user.
    role *BusinessUserRole
    // The user ID associated with this business user.
    userId *string
}
// NewBusinessUserRequest instantiates a new BusinessUserRequest and sets the default values.
func NewBusinessUserRequest()(*BusinessUserRequest) {
    m := &BusinessUserRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBusinessUserRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBusinessUserRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBusinessUserRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BusinessUserRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEmail gets the email property value. The email address associated with this business user.
// returns a *string when successful
func (m *BusinessUserRequest) GetEmail()(*string) {
    return m.email
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BusinessUserRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["role"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessUserRole)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRole(val.(*BusinessUserRole))
        }
        return nil
    }
    res["userId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetRole gets the role property value. The role value for this business user.
// returns a *BusinessUserRole when successful
func (m *BusinessUserRequest) GetRole()(*BusinessUserRole) {
    return m.role
}
// GetUserId gets the userId property value. The user ID associated with this business user.
// returns a *string when successful
func (m *BusinessUserRequest) GetUserId()(*string) {
    return m.userId
}
// Serialize serializes information the current object
func (m *BusinessUserRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    if m.GetRole() != nil {
        cast := (*m.GetRole()).String()
        err := writer.WriteStringValue("role", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userId", m.GetUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BusinessUserRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEmail sets the email property value. The email address associated with this business user.
func (m *BusinessUserRequest) SetEmail(value *string)() {
    m.email = value
}
// SetRole sets the role property value. The role value for this business user.
func (m *BusinessUserRequest) SetRole(value *BusinessUserRole)() {
    m.role = value
}
// SetUserId sets the userId property value. The user ID associated with this business user.
func (m *BusinessUserRequest) SetUserId(value *string)() {
    m.userId = value
}
type BusinessUserRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEmail()(*string)
    GetRole()(*BusinessUserRole)
    GetUserId()(*string)
    SetEmail(value *string)()
    SetRole(value *BusinessUserRole)()
    SetUserId(value *string)()
}
