// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// BusinessResponse aPI response containing business data returned to callers.
type BusinessResponse struct {
    // The wallet balance owned by this business.
    accountBalance *float64
    // The activation value for this business.
    activation BusinessResponse_activationable
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The postal address associated with this business.
    address BusinessResponse_addressable
    // The adminEnablementOverride property
    adminEnablementOverride BusinessResponse_adminEnablementOverrideable
    // The monetary auto refill amount for this business wallet.
    autoRefillAmount i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // Whether auto refill is enabled for this business wallet.
    autoRefillEnabled *bool
    // The auto refill trigger value for this business wallet.
    autoRefillTrigger i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // Defines the supported Billing Plan values.
    billingPlan *BusinessResponse_billingPlan
    // The compliance policy value for this business.
    compliancePolicy BusinessResponse_compliancePolicyable
    // The date and time when the entity was created.
    createdAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The human-readable description of this business.
    description *string
    // The domain name associated with this business.
    domain *string
    // The EIN value for this business.
    ein *string
    // The EIN document value for this business.
    einDocument BusinessResponse_einDocumentable
    // The enabled property
    enabled *bool
    // The unique identifier for the entity.
    id *string
    // The date and time when the entity was last modified, if applicable.
    modifiedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The display name for the entity.
    name *string
    // The phone number associated with this business.
    phone *string
    // The phones included with this business.
    phones []IdNameValueable
    // The secondary name value for this business.
    secondaryName *string
    // Defines the supported Business Setup Step values.
    setupStep *BusinessResponse_setupStep
    // The website value for this business.
    site BusinessResponse_siteable
    // Defines the supported Business Status values.
    status *BusinessResponse_status
    // Stripe billing state owned by this business.
    stripeInfo BusinessResponse_stripeInfoable
    // Defines the supported Subscription Status values.
    subscriptionStatus *BusinessResponse_subscriptionStatus
    // The user value for this business.
    user BusinessResponse_userable
    // The vertical value for this business.
    vertical *string
    // The website URL associated with this business.
    website *string
}
// NewBusinessResponse instantiates a new BusinessResponse and sets the default values.
func NewBusinessResponse()(*BusinessResponse) {
    m := &BusinessResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBusinessResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBusinessResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBusinessResponse(), nil
}
// GetAccountBalance gets the accountBalance property value. The wallet balance owned by this business.
// returns a *float64 when successful
func (m *BusinessResponse) GetAccountBalance()(*float64) {
    return m.accountBalance
}
// GetActivation gets the activation property value. The activation value for this business.
// returns a BusinessResponse_activationable when successful
func (m *BusinessResponse) GetActivation()(BusinessResponse_activationable) {
    return m.activation
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BusinessResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddress gets the address property value. The postal address associated with this business.
// returns a BusinessResponse_addressable when successful
func (m *BusinessResponse) GetAddress()(BusinessResponse_addressable) {
    return m.address
}
// GetAdminEnablementOverride gets the adminEnablementOverride property value. The adminEnablementOverride property
// returns a BusinessResponse_adminEnablementOverrideable when successful
func (m *BusinessResponse) GetAdminEnablementOverride()(BusinessResponse_adminEnablementOverrideable) {
    return m.adminEnablementOverride
}
// GetAutoRefillAmount gets the autoRefillAmount property value. The monetary auto refill amount for this business wallet.
// returns a UntypedNodeable when successful
func (m *BusinessResponse) GetAutoRefillAmount()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.autoRefillAmount
}
// GetAutoRefillEnabled gets the autoRefillEnabled property value. Whether auto refill is enabled for this business wallet.
// returns a *bool when successful
func (m *BusinessResponse) GetAutoRefillEnabled()(*bool) {
    return m.autoRefillEnabled
}
// GetAutoRefillTrigger gets the autoRefillTrigger property value. The auto refill trigger value for this business wallet.
// returns a UntypedNodeable when successful
func (m *BusinessResponse) GetAutoRefillTrigger()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.autoRefillTrigger
}
// GetBillingPlan gets the billingPlan property value. Defines the supported Billing Plan values.
// returns a *BusinessResponse_billingPlan when successful
func (m *BusinessResponse) GetBillingPlan()(*BusinessResponse_billingPlan) {
    return m.billingPlan
}
// GetCompliancePolicy gets the compliancePolicy property value. The compliance policy value for this business.
// returns a BusinessResponse_compliancePolicyable when successful
func (m *BusinessResponse) GetCompliancePolicy()(BusinessResponse_compliancePolicyable) {
    return m.compliancePolicy
}
// GetCreatedAt gets the createdAt property value. The date and time when the entity was created.
// returns a *Time when successful
func (m *BusinessResponse) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdAt
}
// GetDescription gets the description property value. The human-readable description of this business.
// returns a *string when successful
func (m *BusinessResponse) GetDescription()(*string) {
    return m.description
}
// GetDomain gets the domain property value. The domain name associated with this business.
// returns a *string when successful
func (m *BusinessResponse) GetDomain()(*string) {
    return m.domain
}
// GetEin gets the ein property value. The EIN value for this business.
// returns a *string when successful
func (m *BusinessResponse) GetEin()(*string) {
    return m.ein
}
// GetEinDocument gets the einDocument property value. The EIN document value for this business.
// returns a BusinessResponse_einDocumentable when successful
func (m *BusinessResponse) GetEinDocument()(BusinessResponse_einDocumentable) {
    return m.einDocument
}
// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *BusinessResponse) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BusinessResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["accountBalance"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountBalance(val)
        }
        return nil
    }
    res["activation"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_activationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActivation(val.(BusinessResponse_activationable))
        }
        return nil
    }
    res["address"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_addressFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAddress(val.(BusinessResponse_addressable))
        }
        return nil
    }
    res["adminEnablementOverride"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_adminEnablementOverrideFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAdminEnablementOverride(val.(BusinessResponse_adminEnablementOverrideable))
        }
        return nil
    }
    res["autoRefillAmount"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoRefillAmount(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["autoRefillEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoRefillEnabled(val)
        }
        return nil
    }
    res["autoRefillTrigger"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoRefillTrigger(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["billingPlan"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessResponse_billingPlan)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBillingPlan(val.(*BusinessResponse_billingPlan))
        }
        return nil
    }
    res["compliancePolicy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_compliancePolicyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompliancePolicy(val.(BusinessResponse_compliancePolicyable))
        }
        return nil
    }
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDomain(val)
        }
        return nil
    }
    res["ein"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEin(val)
        }
        return nil
    }
    res["einDocument"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_einDocumentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEinDocument(val.(BusinessResponse_einDocumentable))
        }
        return nil
    }
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["modifiedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModifiedAt(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["phone"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhone(val)
        }
        return nil
    }
    res["phones"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateIdNameValueFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]IdNameValueable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(IdNameValueable)
                }
            }
            m.SetPhones(res)
        }
        return nil
    }
    res["secondaryName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSecondaryName(val)
        }
        return nil
    }
    res["setupStep"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessResponse_setupStep)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSetupStep(val.(*BusinessResponse_setupStep))
        }
        return nil
    }
    res["site"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_siteFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSite(val.(BusinessResponse_siteable))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessResponse_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*BusinessResponse_status))
        }
        return nil
    }
    res["stripeInfo"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_stripeInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStripeInfo(val.(BusinessResponse_stripeInfoable))
        }
        return nil
    }
    res["subscriptionStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessResponse_subscriptionStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubscriptionStatus(val.(*BusinessResponse_subscriptionStatus))
        }
        return nil
    }
    res["user"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponse_userFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUser(val.(BusinessResponse_userable))
        }
        return nil
    }
    res["vertical"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVertical(val)
        }
        return nil
    }
    res["website"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWebsite(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The unique identifier for the entity.
// returns a *string when successful
func (m *BusinessResponse) GetId()(*string) {
    return m.id
}
// GetModifiedAt gets the modifiedAt property value. The date and time when the entity was last modified, if applicable.
// returns a *Time when successful
func (m *BusinessResponse) GetModifiedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.modifiedAt
}
// GetName gets the name property value. The display name for the entity.
// returns a *string when successful
func (m *BusinessResponse) GetName()(*string) {
    return m.name
}
// GetPhone gets the phone property value. The phone number associated with this business.
// returns a *string when successful
func (m *BusinessResponse) GetPhone()(*string) {
    return m.phone
}
// GetPhones gets the phones property value. The phones included with this business.
// returns a []IdNameValueable when successful
func (m *BusinessResponse) GetPhones()([]IdNameValueable) {
    return m.phones
}
// GetSecondaryName gets the secondaryName property value. The secondary name value for this business.
// returns a *string when successful
func (m *BusinessResponse) GetSecondaryName()(*string) {
    return m.secondaryName
}
// GetSetupStep gets the setupStep property value. Defines the supported Business Setup Step values.
// returns a *BusinessResponse_setupStep when successful
func (m *BusinessResponse) GetSetupStep()(*BusinessResponse_setupStep) {
    return m.setupStep
}
// GetSite gets the site property value. The website value for this business.
// returns a BusinessResponse_siteable when successful
func (m *BusinessResponse) GetSite()(BusinessResponse_siteable) {
    return m.site
}
// GetStatus gets the status property value. Defines the supported Business Status values.
// returns a *BusinessResponse_status when successful
func (m *BusinessResponse) GetStatus()(*BusinessResponse_status) {
    return m.status
}
// GetStripeInfo gets the stripeInfo property value. Stripe billing state owned by this business.
// returns a BusinessResponse_stripeInfoable when successful
func (m *BusinessResponse) GetStripeInfo()(BusinessResponse_stripeInfoable) {
    return m.stripeInfo
}
// GetSubscriptionStatus gets the subscriptionStatus property value. Defines the supported Subscription Status values.
// returns a *BusinessResponse_subscriptionStatus when successful
func (m *BusinessResponse) GetSubscriptionStatus()(*BusinessResponse_subscriptionStatus) {
    return m.subscriptionStatus
}
// GetUser gets the user property value. The user value for this business.
// returns a BusinessResponse_userable when successful
func (m *BusinessResponse) GetUser()(BusinessResponse_userable) {
    return m.user
}
// GetVertical gets the vertical property value. The vertical value for this business.
// returns a *string when successful
func (m *BusinessResponse) GetVertical()(*string) {
    return m.vertical
}
// GetWebsite gets the website property value. The website URL associated with this business.
// returns a *string when successful
func (m *BusinessResponse) GetWebsite()(*string) {
    return m.website
}
// Serialize serializes information the current object
func (m *BusinessResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("accountBalance", m.GetAccountBalance())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("activation", m.GetActivation())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("address", m.GetAddress())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("adminEnablementOverride", m.GetAdminEnablementOverride())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("autoRefillAmount", m.GetAutoRefillAmount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("autoRefillEnabled", m.GetAutoRefillEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("autoRefillTrigger", m.GetAutoRefillTrigger())
        if err != nil {
            return err
        }
    }
    if m.GetBillingPlan() != nil {
        cast := (*m.GetBillingPlan()).String()
        err := writer.WriteStringValue("billingPlan", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("compliancePolicy", m.GetCompliancePolicy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("domain", m.GetDomain())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ein", m.GetEin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("einDocument", m.GetEinDocument())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("modifiedAt", m.GetModifiedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("phone", m.GetPhone())
        if err != nil {
            return err
        }
    }
    if m.GetPhones() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPhones()))
        for i, v := range m.GetPhones() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("phones", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("secondaryName", m.GetSecondaryName())
        if err != nil {
            return err
        }
    }
    if m.GetSetupStep() != nil {
        cast := (*m.GetSetupStep()).String()
        err := writer.WriteStringValue("setupStep", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("site", m.GetSite())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("stripeInfo", m.GetStripeInfo())
        if err != nil {
            return err
        }
    }
    if m.GetSubscriptionStatus() != nil {
        cast := (*m.GetSubscriptionStatus()).String()
        err := writer.WriteStringValue("subscriptionStatus", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("user", m.GetUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("vertical", m.GetVertical())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("website", m.GetWebsite())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccountBalance sets the accountBalance property value. The wallet balance owned by this business.
func (m *BusinessResponse) SetAccountBalance(value *float64)() {
    m.accountBalance = value
}
// SetActivation sets the activation property value. The activation value for this business.
func (m *BusinessResponse) SetActivation(value BusinessResponse_activationable)() {
    m.activation = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BusinessResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddress sets the address property value. The postal address associated with this business.
func (m *BusinessResponse) SetAddress(value BusinessResponse_addressable)() {
    m.address = value
}
// SetAdminEnablementOverride sets the adminEnablementOverride property value. The adminEnablementOverride property
func (m *BusinessResponse) SetAdminEnablementOverride(value BusinessResponse_adminEnablementOverrideable)() {
    m.adminEnablementOverride = value
}
// SetAutoRefillAmount sets the autoRefillAmount property value. The monetary auto refill amount for this business wallet.
func (m *BusinessResponse) SetAutoRefillAmount(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.autoRefillAmount = value
}
// SetAutoRefillEnabled sets the autoRefillEnabled property value. Whether auto refill is enabled for this business wallet.
func (m *BusinessResponse) SetAutoRefillEnabled(value *bool)() {
    m.autoRefillEnabled = value
}
// SetAutoRefillTrigger sets the autoRefillTrigger property value. The auto refill trigger value for this business wallet.
func (m *BusinessResponse) SetAutoRefillTrigger(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.autoRefillTrigger = value
}
// SetBillingPlan sets the billingPlan property value. Defines the supported Billing Plan values.
func (m *BusinessResponse) SetBillingPlan(value *BusinessResponse_billingPlan)() {
    m.billingPlan = value
}
// SetCompliancePolicy sets the compliancePolicy property value. The compliance policy value for this business.
func (m *BusinessResponse) SetCompliancePolicy(value BusinessResponse_compliancePolicyable)() {
    m.compliancePolicy = value
}
// SetCreatedAt sets the createdAt property value. The date and time when the entity was created.
func (m *BusinessResponse) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdAt = value
}
// SetDescription sets the description property value. The human-readable description of this business.
func (m *BusinessResponse) SetDescription(value *string)() {
    m.description = value
}
// SetDomain sets the domain property value. The domain name associated with this business.
func (m *BusinessResponse) SetDomain(value *string)() {
    m.domain = value
}
// SetEin sets the ein property value. The EIN value for this business.
func (m *BusinessResponse) SetEin(value *string)() {
    m.ein = value
}
// SetEinDocument sets the einDocument property value. The EIN document value for this business.
func (m *BusinessResponse) SetEinDocument(value BusinessResponse_einDocumentable)() {
    m.einDocument = value
}
// SetEnabled sets the enabled property value. The enabled property
func (m *BusinessResponse) SetEnabled(value *bool)() {
    m.enabled = value
}
// SetId sets the id property value. The unique identifier for the entity.
func (m *BusinessResponse) SetId(value *string)() {
    m.id = value
}
// SetModifiedAt sets the modifiedAt property value. The date and time when the entity was last modified, if applicable.
func (m *BusinessResponse) SetModifiedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.modifiedAt = value
}
// SetName sets the name property value. The display name for the entity.
func (m *BusinessResponse) SetName(value *string)() {
    m.name = value
}
// SetPhone sets the phone property value. The phone number associated with this business.
func (m *BusinessResponse) SetPhone(value *string)() {
    m.phone = value
}
// SetPhones sets the phones property value. The phones included with this business.
func (m *BusinessResponse) SetPhones(value []IdNameValueable)() {
    m.phones = value
}
// SetSecondaryName sets the secondaryName property value. The secondary name value for this business.
func (m *BusinessResponse) SetSecondaryName(value *string)() {
    m.secondaryName = value
}
// SetSetupStep sets the setupStep property value. Defines the supported Business Setup Step values.
func (m *BusinessResponse) SetSetupStep(value *BusinessResponse_setupStep)() {
    m.setupStep = value
}
// SetSite sets the site property value. The website value for this business.
func (m *BusinessResponse) SetSite(value BusinessResponse_siteable)() {
    m.site = value
}
// SetStatus sets the status property value. Defines the supported Business Status values.
func (m *BusinessResponse) SetStatus(value *BusinessResponse_status)() {
    m.status = value
}
// SetStripeInfo sets the stripeInfo property value. Stripe billing state owned by this business.
func (m *BusinessResponse) SetStripeInfo(value BusinessResponse_stripeInfoable)() {
    m.stripeInfo = value
}
// SetSubscriptionStatus sets the subscriptionStatus property value. Defines the supported Subscription Status values.
func (m *BusinessResponse) SetSubscriptionStatus(value *BusinessResponse_subscriptionStatus)() {
    m.subscriptionStatus = value
}
// SetUser sets the user property value. The user value for this business.
func (m *BusinessResponse) SetUser(value BusinessResponse_userable)() {
    m.user = value
}
// SetVertical sets the vertical property value. The vertical value for this business.
func (m *BusinessResponse) SetVertical(value *string)() {
    m.vertical = value
}
// SetWebsite sets the website property value. The website URL associated with this business.
func (m *BusinessResponse) SetWebsite(value *string)() {
    m.website = value
}
type BusinessResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountBalance()(*float64)
    GetActivation()(BusinessResponse_activationable)
    GetAddress()(BusinessResponse_addressable)
    GetAdminEnablementOverride()(BusinessResponse_adminEnablementOverrideable)
    GetAutoRefillAmount()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetAutoRefillEnabled()(*bool)
    GetAutoRefillTrigger()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetBillingPlan()(*BusinessResponse_billingPlan)
    GetCompliancePolicy()(BusinessResponse_compliancePolicyable)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDescription()(*string)
    GetDomain()(*string)
    GetEin()(*string)
    GetEinDocument()(BusinessResponse_einDocumentable)
    GetEnabled()(*bool)
    GetId()(*string)
    GetModifiedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetName()(*string)
    GetPhone()(*string)
    GetPhones()([]IdNameValueable)
    GetSecondaryName()(*string)
    GetSetupStep()(*BusinessResponse_setupStep)
    GetSite()(BusinessResponse_siteable)
    GetStatus()(*BusinessResponse_status)
    GetStripeInfo()(BusinessResponse_stripeInfoable)
    GetSubscriptionStatus()(*BusinessResponse_subscriptionStatus)
    GetUser()(BusinessResponse_userable)
    GetVertical()(*string)
    GetWebsite()(*string)
    SetAccountBalance(value *float64)()
    SetActivation(value BusinessResponse_activationable)()
    SetAddress(value BusinessResponse_addressable)()
    SetAdminEnablementOverride(value BusinessResponse_adminEnablementOverrideable)()
    SetAutoRefillAmount(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetAutoRefillEnabled(value *bool)()
    SetAutoRefillTrigger(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetBillingPlan(value *BusinessResponse_billingPlan)()
    SetCompliancePolicy(value BusinessResponse_compliancePolicyable)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDescription(value *string)()
    SetDomain(value *string)()
    SetEin(value *string)()
    SetEinDocument(value BusinessResponse_einDocumentable)()
    SetEnabled(value *bool)()
    SetId(value *string)()
    SetModifiedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetName(value *string)()
    SetPhone(value *string)()
    SetPhones(value []IdNameValueable)()
    SetSecondaryName(value *string)()
    SetSetupStep(value *BusinessResponse_setupStep)()
    SetSite(value BusinessResponse_siteable)()
    SetStatus(value *BusinessResponse_status)()
    SetStripeInfo(value BusinessResponse_stripeInfoable)()
    SetSubscriptionStatus(value *BusinessResponse_subscriptionStatus)()
    SetUser(value BusinessResponse_userable)()
    SetVertical(value *string)()
    SetWebsite(value *string)()
}
