// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the supported Business Invitation Status values.
type BusinessInvitationStatus int

const (
    PENDING_BUSINESSINVITATIONSTATUS BusinessInvitationStatus = iota
    ACCEPTED_BUSINESSINVITATIONSTATUS
    EXPIRED_BUSINESSINVITATIONSTATUS
    REVOKED_BUSINESSINVITATIONSTATUS
    RESENT_BUSINESSINVITATIONSTATUS
    FAILEDTOSEND_BUSINESSINVITATIONSTATUS
)

func (i BusinessInvitationStatus) String() string {
    return []string{"Pending", "Accepted", "Expired", "Revoked", "Resent", "Failed to send"}[i]
}
func ParseBusinessInvitationStatus(v string) (any, error) {
    result := PENDING_BUSINESSINVITATIONSTATUS
    switch v {
        case "Pending":
            result = PENDING_BUSINESSINVITATIONSTATUS
        case "Accepted":
            result = ACCEPTED_BUSINESSINVITATIONSTATUS
        case "Expired":
            result = EXPIRED_BUSINESSINVITATIONSTATUS
        case "Revoked":
            result = REVOKED_BUSINESSINVITATIONSTATUS
        case "Resent":
            result = RESENT_BUSINESSINVITATIONSTATUS
        case "Failed to send":
            result = FAILEDTOSEND_BUSINESSINVITATIONSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeBusinessInvitationStatus(values []BusinessInvitationStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i BusinessInvitationStatus) isMultiValue() bool {
    return false
}
