// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// BusinessRequest_address postal address for the business, lead, or contact represented by this business profile request.
type BusinessRequest_address struct {
    StreetAddress
}
// NewBusinessRequest_address instantiates a new BusinessRequest_address and sets the default values.
func NewBusinessRequest_address()(*BusinessRequest_address) {
    m := &BusinessRequest_address{
        StreetAddress: *NewStreetAddress(),
    }
    return m
}
// CreateBusinessRequest_addressFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBusinessRequest_addressFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBusinessRequest_address(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BusinessRequest_address) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.StreetAddress.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *BusinessRequest_address) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.StreetAddress.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type BusinessRequest_addressable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    StreetAddressable
}
