// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ConversationResponse aPI response containing conversation data returned to callers.
type ConversationResponse struct {
    // The active outbound phone number ID associated with this conversation.
    activeOutboundPhoneNumberId *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The archivedAt property
    archivedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Defines why a lead was removed from the active working pipeline.
    archiveReason *int32
    // The current lifecycle disposition for the conversation's lead.
    currentDisposition ConversationResponse_currentDispositionable
    // The first name value for this conversation.
    firstName *string
    // The unique ID for this conversation.
    id *string
    // The isArchived property
    isArchived *bool
    // Whether this conversation is unread.
    isUnread *bool
    // The date and time for the last event at value on this conversation.
    lastEventAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The date and time for the last name value on this conversation.
    lastName *string
    // The date and time for the last snippet value on this conversation.
    lastSnippet *string
    // The lead ID associated with this conversation.
    leadId *string
    // The lead's primary contact phone number for this conversation.
    leadPhoneNumber *string
    // The recommended next action for the inbox user.
    nextStep *string
    // The outbound phone number override ID associated with this conversation.
    outboundPhoneNumberOverrideId *string
    // The Leadping sender phone number associated with this conversation.
    phoneNumber ConversationResponse_phoneNumberable
    // Defines the customer-facing operational status for an inbox conversation.
    status *ConversationResponse_status
    // The human-readable reason explaining the current conversation status.
    statusReason *string
}
// NewConversationResponse instantiates a new ConversationResponse and sets the default values.
func NewConversationResponse()(*ConversationResponse) {
    m := &ConversationResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateConversationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateConversationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewConversationResponse(), nil
}
// GetActiveOutboundPhoneNumberId gets the activeOutboundPhoneNumberId property value. The active outbound phone number ID associated with this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetActiveOutboundPhoneNumberId()(*string) {
    return m.activeOutboundPhoneNumberId
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ConversationResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetArchivedAt gets the archivedAt property value. The archivedAt property
// returns a *Time when successful
func (m *ConversationResponse) GetArchivedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.archivedAt
}
// GetArchiveReason gets the archiveReason property value. Defines why a lead was removed from the active working pipeline.
// returns a *int32 when successful
func (m *ConversationResponse) GetArchiveReason()(*int32) {
    return m.archiveReason
}
// GetCurrentDisposition gets the currentDisposition property value. The current lifecycle disposition for the conversation's lead.
// returns a ConversationResponse_currentDispositionable when successful
func (m *ConversationResponse) GetCurrentDisposition()(ConversationResponse_currentDispositionable) {
    return m.currentDisposition
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ConversationResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["activeOutboundPhoneNumberId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActiveOutboundPhoneNumberId(val)
        }
        return nil
    }
    res["archivedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetArchivedAt(val)
        }
        return nil
    }
    res["archiveReason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetArchiveReason(val)
        }
        return nil
    }
    res["currentDisposition"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateConversationResponse_currentDispositionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCurrentDisposition(val.(ConversationResponse_currentDispositionable))
        }
        return nil
    }
    res["firstName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirstName(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["isArchived"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsArchived(val)
        }
        return nil
    }
    res["isUnread"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsUnread(val)
        }
        return nil
    }
    res["lastEventAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastEventAt(val)
        }
        return nil
    }
    res["lastName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastName(val)
        }
        return nil
    }
    res["lastSnippet"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastSnippet(val)
        }
        return nil
    }
    res["leadId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLeadId(val)
        }
        return nil
    }
    res["leadPhoneNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLeadPhoneNumber(val)
        }
        return nil
    }
    res["nextStep"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNextStep(val)
        }
        return nil
    }
    res["outboundPhoneNumberOverrideId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOutboundPhoneNumberOverrideId(val)
        }
        return nil
    }
    res["phoneNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateConversationResponse_phoneNumberFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhoneNumber(val.(ConversationResponse_phoneNumberable))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseConversationResponse_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*ConversationResponse_status))
        }
        return nil
    }
    res["statusReason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatusReason(val)
        }
        return nil
    }
    return res
}
// GetFirstName gets the firstName property value. The first name value for this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetFirstName()(*string) {
    return m.firstName
}
// GetId gets the id property value. The unique ID for this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetId()(*string) {
    return m.id
}
// GetIsArchived gets the isArchived property value. The isArchived property
// returns a *bool when successful
func (m *ConversationResponse) GetIsArchived()(*bool) {
    return m.isArchived
}
// GetIsUnread gets the isUnread property value. Whether this conversation is unread.
// returns a *bool when successful
func (m *ConversationResponse) GetIsUnread()(*bool) {
    return m.isUnread
}
// GetLastEventAt gets the lastEventAt property value. The date and time for the last event at value on this conversation.
// returns a *Time when successful
func (m *ConversationResponse) GetLastEventAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.lastEventAt
}
// GetLastName gets the lastName property value. The date and time for the last name value on this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetLastName()(*string) {
    return m.lastName
}
// GetLastSnippet gets the lastSnippet property value. The date and time for the last snippet value on this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetLastSnippet()(*string) {
    return m.lastSnippet
}
// GetLeadId gets the leadId property value. The lead ID associated with this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetLeadId()(*string) {
    return m.leadId
}
// GetLeadPhoneNumber gets the leadPhoneNumber property value. The lead's primary contact phone number for this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetLeadPhoneNumber()(*string) {
    return m.leadPhoneNumber
}
// GetNextStep gets the nextStep property value. The recommended next action for the inbox user.
// returns a *string when successful
func (m *ConversationResponse) GetNextStep()(*string) {
    return m.nextStep
}
// GetOutboundPhoneNumberOverrideId gets the outboundPhoneNumberOverrideId property value. The outbound phone number override ID associated with this conversation.
// returns a *string when successful
func (m *ConversationResponse) GetOutboundPhoneNumberOverrideId()(*string) {
    return m.outboundPhoneNumberOverrideId
}
// GetPhoneNumber gets the phoneNumber property value. The Leadping sender phone number associated with this conversation.
// returns a ConversationResponse_phoneNumberable when successful
func (m *ConversationResponse) GetPhoneNumber()(ConversationResponse_phoneNumberable) {
    return m.phoneNumber
}
// GetStatus gets the status property value. Defines the customer-facing operational status for an inbox conversation.
// returns a *ConversationResponse_status when successful
func (m *ConversationResponse) GetStatus()(*ConversationResponse_status) {
    return m.status
}
// GetStatusReason gets the statusReason property value. The human-readable reason explaining the current conversation status.
// returns a *string when successful
func (m *ConversationResponse) GetStatusReason()(*string) {
    return m.statusReason
}
// Serialize serializes information the current object
func (m *ConversationResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("activeOutboundPhoneNumberId", m.GetActiveOutboundPhoneNumberId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("archivedAt", m.GetArchivedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("archiveReason", m.GetArchiveReason())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("currentDisposition", m.GetCurrentDisposition())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("firstName", m.GetFirstName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isArchived", m.GetIsArchived())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isUnread", m.GetIsUnread())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("lastEventAt", m.GetLastEventAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("lastName", m.GetLastName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("lastSnippet", m.GetLastSnippet())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("leadId", m.GetLeadId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("leadPhoneNumber", m.GetLeadPhoneNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("nextStep", m.GetNextStep())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("outboundPhoneNumberOverrideId", m.GetOutboundPhoneNumberOverrideId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("phoneNumber", m.GetPhoneNumber())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("statusReason", m.GetStatusReason())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActiveOutboundPhoneNumberId sets the activeOutboundPhoneNumberId property value. The active outbound phone number ID associated with this conversation.
func (m *ConversationResponse) SetActiveOutboundPhoneNumberId(value *string)() {
    m.activeOutboundPhoneNumberId = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ConversationResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetArchivedAt sets the archivedAt property value. The archivedAt property
func (m *ConversationResponse) SetArchivedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.archivedAt = value
}
// SetArchiveReason sets the archiveReason property value. Defines why a lead was removed from the active working pipeline.
func (m *ConversationResponse) SetArchiveReason(value *int32)() {
    m.archiveReason = value
}
// SetCurrentDisposition sets the currentDisposition property value. The current lifecycle disposition for the conversation's lead.
func (m *ConversationResponse) SetCurrentDisposition(value ConversationResponse_currentDispositionable)() {
    m.currentDisposition = value
}
// SetFirstName sets the firstName property value. The first name value for this conversation.
func (m *ConversationResponse) SetFirstName(value *string)() {
    m.firstName = value
}
// SetId sets the id property value. The unique ID for this conversation.
func (m *ConversationResponse) SetId(value *string)() {
    m.id = value
}
// SetIsArchived sets the isArchived property value. The isArchived property
func (m *ConversationResponse) SetIsArchived(value *bool)() {
    m.isArchived = value
}
// SetIsUnread sets the isUnread property value. Whether this conversation is unread.
func (m *ConversationResponse) SetIsUnread(value *bool)() {
    m.isUnread = value
}
// SetLastEventAt sets the lastEventAt property value. The date and time for the last event at value on this conversation.
func (m *ConversationResponse) SetLastEventAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.lastEventAt = value
}
// SetLastName sets the lastName property value. The date and time for the last name value on this conversation.
func (m *ConversationResponse) SetLastName(value *string)() {
    m.lastName = value
}
// SetLastSnippet sets the lastSnippet property value. The date and time for the last snippet value on this conversation.
func (m *ConversationResponse) SetLastSnippet(value *string)() {
    m.lastSnippet = value
}
// SetLeadId sets the leadId property value. The lead ID associated with this conversation.
func (m *ConversationResponse) SetLeadId(value *string)() {
    m.leadId = value
}
// SetLeadPhoneNumber sets the leadPhoneNumber property value. The lead's primary contact phone number for this conversation.
func (m *ConversationResponse) SetLeadPhoneNumber(value *string)() {
    m.leadPhoneNumber = value
}
// SetNextStep sets the nextStep property value. The recommended next action for the inbox user.
func (m *ConversationResponse) SetNextStep(value *string)() {
    m.nextStep = value
}
// SetOutboundPhoneNumberOverrideId sets the outboundPhoneNumberOverrideId property value. The outbound phone number override ID associated with this conversation.
func (m *ConversationResponse) SetOutboundPhoneNumberOverrideId(value *string)() {
    m.outboundPhoneNumberOverrideId = value
}
// SetPhoneNumber sets the phoneNumber property value. The Leadping sender phone number associated with this conversation.
func (m *ConversationResponse) SetPhoneNumber(value ConversationResponse_phoneNumberable)() {
    m.phoneNumber = value
}
// SetStatus sets the status property value. Defines the customer-facing operational status for an inbox conversation.
func (m *ConversationResponse) SetStatus(value *ConversationResponse_status)() {
    m.status = value
}
// SetStatusReason sets the statusReason property value. The human-readable reason explaining the current conversation status.
func (m *ConversationResponse) SetStatusReason(value *string)() {
    m.statusReason = value
}
type ConversationResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActiveOutboundPhoneNumberId()(*string)
    GetArchivedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetArchiveReason()(*int32)
    GetCurrentDisposition()(ConversationResponse_currentDispositionable)
    GetFirstName()(*string)
    GetId()(*string)
    GetIsArchived()(*bool)
    GetIsUnread()(*bool)
    GetLastEventAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetLastName()(*string)
    GetLastSnippet()(*string)
    GetLeadId()(*string)
    GetLeadPhoneNumber()(*string)
    GetNextStep()(*string)
    GetOutboundPhoneNumberOverrideId()(*string)
    GetPhoneNumber()(ConversationResponse_phoneNumberable)
    GetStatus()(*ConversationResponse_status)
    GetStatusReason()(*string)
    SetActiveOutboundPhoneNumberId(value *string)()
    SetArchivedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetArchiveReason(value *int32)()
    SetCurrentDisposition(value ConversationResponse_currentDispositionable)()
    SetFirstName(value *string)()
    SetId(value *string)()
    SetIsArchived(value *bool)()
    SetIsUnread(value *bool)()
    SetLastEventAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetLastName(value *string)()
    SetLastSnippet(value *string)()
    SetLeadId(value *string)()
    SetLeadPhoneNumber(value *string)()
    SetNextStep(value *string)()
    SetOutboundPhoneNumberOverrideId(value *string)()
    SetPhoneNumber(value ConversationResponse_phoneNumberable)()
    SetStatus(value *ConversationResponse_status)()
    SetStatusReason(value *string)()
}
