// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CurrentDispositionSummary summary schema for Leadping API current disposition summary data used in dashboards and reports.
type CurrentDispositionSummary struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Controlled disposition categories used for reporting, automation, and analytics.
    category *CurrentDispositionSummary_category
    // UTC timestamp when the disposition last changed.
    changedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Automation ID that last changed the disposition.
    changedByAutomationId *string
    // User ID of the person who last changed the disposition.
    changedByUserId *string
    // Human-readable display name shown for this current disposition summary.
    displayName *string
    // Unique Leadping identifier for this current disposition summary.
    id *string
    // Current disposition outcome assigned to the lead.
    outcome *string
    // Known sources that can change a lead's current disposition.
    source *CurrentDispositionSummary_source
}
// NewCurrentDispositionSummary instantiates a new CurrentDispositionSummary and sets the default values.
func NewCurrentDispositionSummary()(*CurrentDispositionSummary) {
    m := &CurrentDispositionSummary{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCurrentDispositionSummaryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCurrentDispositionSummaryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCurrentDispositionSummary(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CurrentDispositionSummary) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCategory gets the category property value. Controlled disposition categories used for reporting, automation, and analytics.
// returns a *CurrentDispositionSummary_category when successful
func (m *CurrentDispositionSummary) GetCategory()(*CurrentDispositionSummary_category) {
    return m.category
}
// GetChangedAt gets the changedAt property value. UTC timestamp when the disposition last changed.
// returns a *Time when successful
func (m *CurrentDispositionSummary) GetChangedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.changedAt
}
// GetChangedByAutomationId gets the changedByAutomationId property value. Automation ID that last changed the disposition.
// returns a *string when successful
func (m *CurrentDispositionSummary) GetChangedByAutomationId()(*string) {
    return m.changedByAutomationId
}
// GetChangedByUserId gets the changedByUserId property value. User ID of the person who last changed the disposition.
// returns a *string when successful
func (m *CurrentDispositionSummary) GetChangedByUserId()(*string) {
    return m.changedByUserId
}
// GetDisplayName gets the displayName property value. Human-readable display name shown for this current disposition summary.
// returns a *string when successful
func (m *CurrentDispositionSummary) GetDisplayName()(*string) {
    return m.displayName
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CurrentDispositionSummary) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["category"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCurrentDispositionSummary_category)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCategory(val.(*CurrentDispositionSummary_category))
        }
        return nil
    }
    res["changedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChangedAt(val)
        }
        return nil
    }
    res["changedByAutomationId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChangedByAutomationId(val)
        }
        return nil
    }
    res["changedByUserId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChangedByUserId(val)
        }
        return nil
    }
    res["displayName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDisplayName(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["outcome"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOutcome(val)
        }
        return nil
    }
    res["source"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCurrentDispositionSummary_source)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSource(val.(*CurrentDispositionSummary_source))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Unique Leadping identifier for this current disposition summary.
// returns a *string when successful
func (m *CurrentDispositionSummary) GetId()(*string) {
    return m.id
}
// GetOutcome gets the outcome property value. Current disposition outcome assigned to the lead.
// returns a *string when successful
func (m *CurrentDispositionSummary) GetOutcome()(*string) {
    return m.outcome
}
// GetSource gets the source property value. Known sources that can change a lead's current disposition.
// returns a *CurrentDispositionSummary_source when successful
func (m *CurrentDispositionSummary) GetSource()(*CurrentDispositionSummary_source) {
    return m.source
}
// Serialize serializes information the current object
func (m *CurrentDispositionSummary) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCategory() != nil {
        cast := (*m.GetCategory()).String()
        err := writer.WriteStringValue("category", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("changedAt", m.GetChangedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("changedByAutomationId", m.GetChangedByAutomationId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("changedByUserId", m.GetChangedByUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("displayName", m.GetDisplayName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("outcome", m.GetOutcome())
        if err != nil {
            return err
        }
    }
    if m.GetSource() != nil {
        cast := (*m.GetSource()).String()
        err := writer.WriteStringValue("source", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CurrentDispositionSummary) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCategory sets the category property value. Controlled disposition categories used for reporting, automation, and analytics.
func (m *CurrentDispositionSummary) SetCategory(value *CurrentDispositionSummary_category)() {
    m.category = value
}
// SetChangedAt sets the changedAt property value. UTC timestamp when the disposition last changed.
func (m *CurrentDispositionSummary) SetChangedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.changedAt = value
}
// SetChangedByAutomationId sets the changedByAutomationId property value. Automation ID that last changed the disposition.
func (m *CurrentDispositionSummary) SetChangedByAutomationId(value *string)() {
    m.changedByAutomationId = value
}
// SetChangedByUserId sets the changedByUserId property value. User ID of the person who last changed the disposition.
func (m *CurrentDispositionSummary) SetChangedByUserId(value *string)() {
    m.changedByUserId = value
}
// SetDisplayName sets the displayName property value. Human-readable display name shown for this current disposition summary.
func (m *CurrentDispositionSummary) SetDisplayName(value *string)() {
    m.displayName = value
}
// SetId sets the id property value. Unique Leadping identifier for this current disposition summary.
func (m *CurrentDispositionSummary) SetId(value *string)() {
    m.id = value
}
// SetOutcome sets the outcome property value. Current disposition outcome assigned to the lead.
func (m *CurrentDispositionSummary) SetOutcome(value *string)() {
    m.outcome = value
}
// SetSource sets the source property value. Known sources that can change a lead's current disposition.
func (m *CurrentDispositionSummary) SetSource(value *CurrentDispositionSummary_source)() {
    m.source = value
}
type CurrentDispositionSummaryable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCategory()(*CurrentDispositionSummary_category)
    GetChangedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetChangedByAutomationId()(*string)
    GetChangedByUserId()(*string)
    GetDisplayName()(*string)
    GetId()(*string)
    GetOutcome()(*string)
    GetSource()(*CurrentDispositionSummary_source)
    SetCategory(value *CurrentDispositionSummary_category)()
    SetChangedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetChangedByAutomationId(value *string)()
    SetChangedByUserId(value *string)()
    SetDisplayName(value *string)()
    SetId(value *string)()
    SetOutcome(value *string)()
    SetSource(value *CurrentDispositionSummary_source)()
}
