// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the type of product feedback submitted from inside Leadping.
type FeedbackCreateRequest_type int

const (
    BUG_FEEDBACKCREATEREQUEST_TYPE FeedbackCreateRequest_type = iota
    CONFUSING_FEEDBACKCREATEREQUEST_TYPE
    FEATURE_REQUEST_FEEDBACKCREATEREQUEST_TYPE
    MISSING_CAPABILITY_FEEDBACKCREATEREQUEST_TYPE
    OTHER_FEEDBACKCREATEREQUEST_TYPE
)

func (i FeedbackCreateRequest_type) String() string {
    return []string{"bug", "confusing", "feature_request", "missing_capability", "other"}[i]
}
func ParseFeedbackCreateRequest_type(v string) (any, error) {
    result := BUG_FEEDBACKCREATEREQUEST_TYPE
    switch v {
        case "bug":
            result = BUG_FEEDBACKCREATEREQUEST_TYPE
        case "confusing":
            result = CONFUSING_FEEDBACKCREATEREQUEST_TYPE
        case "feature_request":
            result = FEATURE_REQUEST_FEEDBACKCREATEREQUEST_TYPE
        case "missing_capability":
            result = MISSING_CAPABILITY_FEEDBACKCREATEREQUEST_TYPE
        case "other":
            result = OTHER_FEEDBACKCREATEREQUEST_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeFeedbackCreateRequest_type(values []FeedbackCreateRequest_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i FeedbackCreateRequest_type) isMultiValue() bool {
    return false
}
