// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the source that requested outbound delivery.
type InitiateCallRequest_outboundSource int

const (
    MANUAL_INITIATECALLREQUEST_OUTBOUNDSOURCE InitiateCallRequest_outboundSource = iota
    AUTOMATION_INITIATECALLREQUEST_OUTBOUNDSOURCE
    CAMPAIGN_INITIATECALLREQUEST_OUTBOUNDSOURCE
    IMPORT_INITIATECALLREQUEST_OUTBOUNDSOURCE
    API_INITIATECALLREQUEST_OUTBOUNDSOURCE
    SYSTEM_NOTIFICATION_INITIATECALLREQUEST_OUTBOUNDSOURCE
    WARMUP_INITIATECALLREQUEST_OUTBOUNDSOURCE
    RETRY_INITIATECALLREQUEST_OUTBOUNDSOURCE
)

func (i InitiateCallRequest_outboundSource) String() string {
    return []string{"manual", "automation", "campaign", "import", "api", "system_notification", "warmup", "retry"}[i]
}
func ParseInitiateCallRequest_outboundSource(v string) (any, error) {
    result := MANUAL_INITIATECALLREQUEST_OUTBOUNDSOURCE
    switch v {
        case "manual":
            result = MANUAL_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "automation":
            result = AUTOMATION_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "campaign":
            result = CAMPAIGN_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "import":
            result = IMPORT_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "api":
            result = API_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "system_notification":
            result = SYSTEM_NOTIFICATION_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "warmup":
            result = WARMUP_INITIATECALLREQUEST_OUTBOUNDSOURCE
        case "retry":
            result = RETRY_INITIATECALLREQUEST_OUTBOUNDSOURCE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeInitiateCallRequest_outboundSource(values []InitiateCallRequest_outboundSource) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i InitiateCallRequest_outboundSource) isMultiValue() bool {
    return false
}
