// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// LeadResponse_phoneIdentity canonical phone identity and provider lookup details for this lead.
type LeadResponse_phoneIdentity struct {
    PhoneIdentityResponse
}
// NewLeadResponse_phoneIdentity instantiates a new LeadResponse_phoneIdentity and sets the default values.
func NewLeadResponse_phoneIdentity()(*LeadResponse_phoneIdentity) {
    m := &LeadResponse_phoneIdentity{
        PhoneIdentityResponse: *NewPhoneIdentityResponse(),
    }
    return m
}
// CreateLeadResponse_phoneIdentityFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLeadResponse_phoneIdentityFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLeadResponse_phoneIdentity(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LeadResponse_phoneIdentity) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.PhoneIdentityResponse.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *LeadResponse_phoneIdentity) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.PhoneIdentityResponse.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type LeadResponse_phoneIdentityable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PhoneIdentityResponseable
}
