// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the supported Marital Status Type values.
type LeadProfile_maritalStatus int

const (
    MARRIED_LEADPROFILE_MARITALSTATUS LeadProfile_maritalStatus = iota
    SINGLE_LEADPROFILE_MARITALSTATUS
    WIDOW_LEADPROFILE_MARITALSTATUS
    SEPARATED_LEADPROFILE_MARITALSTATUS
    DIVORCED_LEADPROFILE_MARITALSTATUS
)

func (i LeadProfile_maritalStatus) String() string {
    return []string{"Married", "Single", "Widow", "Separated", "Divorced"}[i]
}
func ParseLeadProfile_maritalStatus(v string) (any, error) {
    result := MARRIED_LEADPROFILE_MARITALSTATUS
    switch v {
        case "Married":
            result = MARRIED_LEADPROFILE_MARITALSTATUS
        case "Single":
            result = SINGLE_LEADPROFILE_MARITALSTATUS
        case "Widow":
            result = WIDOW_LEADPROFILE_MARITALSTATUS
        case "Separated":
            result = SEPARATED_LEADPROFILE_MARITALSTATUS
        case "Divorced":
            result = DIVORCED_LEADPROFILE_MARITALSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeLeadProfile_maritalStatus(values []LeadProfile_maritalStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i LeadProfile_maritalStatus) isMultiValue() bool {
    return false
}
