// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Defines the supported Customer Activation Status values.
type OrganizationSwitchOption_activationStatus int

const (
    DRAFTONBOARDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS OrganizationSwitchOption_activationStatus = iota
    PAYMENTMETHODPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    PAYMENTMETHODCONFIRMED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    SUBSCRIPTIONPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    SUBSCRIPTIONRECEIVED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    SUBSCRIPTIONACTIVE_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    LAUNCHREVIEWPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    TELEPHONYPROVISIONINGPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    TELEPHONYPARTIALLYPROVISIONED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    TELEPHONYREADY_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    AWAITINGREVIEW_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    DOMAINSELECTION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    WEBSITESETUP_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    COMPLIANCEREGISTRATION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    READYFORAPPROVAL_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    ACTIVE_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    FAILED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    BLOCKED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    BLOCKEDREQUIRESOPERATORACTION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    MANUALLYBYPASSED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
)

func (i OrganizationSwitchOption_activationStatus) String() string {
    return []string{"DraftOnboarding", "PaymentMethodPending", "PaymentMethodConfirmed", "SubscriptionPending", "SubscriptionReceived", "SubscriptionActive", "LaunchReviewPending", "TelephonyProvisioningPending", "TelephonyPartiallyProvisioned", "TelephonyReady", "AwaitingReview", "DomainSelection", "WebsiteSetup", "ComplianceRegistration", "ReadyForApproval", "Active", "Failed", "Blocked", "BlockedRequiresOperatorAction", "ManuallyBypassed"}[i]
}
func ParseOrganizationSwitchOption_activationStatus(v string) (any, error) {
    result := DRAFTONBOARDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
    switch v {
        case "DraftOnboarding":
            result = DRAFTONBOARDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "PaymentMethodPending":
            result = PAYMENTMETHODPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "PaymentMethodConfirmed":
            result = PAYMENTMETHODCONFIRMED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "SubscriptionPending":
            result = SUBSCRIPTIONPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "SubscriptionReceived":
            result = SUBSCRIPTIONRECEIVED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "SubscriptionActive":
            result = SUBSCRIPTIONACTIVE_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "LaunchReviewPending":
            result = LAUNCHREVIEWPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "TelephonyProvisioningPending":
            result = TELEPHONYPROVISIONINGPENDING_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "TelephonyPartiallyProvisioned":
            result = TELEPHONYPARTIALLYPROVISIONED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "TelephonyReady":
            result = TELEPHONYREADY_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "AwaitingReview":
            result = AWAITINGREVIEW_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "DomainSelection":
            result = DOMAINSELECTION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "WebsiteSetup":
            result = WEBSITESETUP_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "ComplianceRegistration":
            result = COMPLIANCEREGISTRATION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "ReadyForApproval":
            result = READYFORAPPROVAL_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "Active":
            result = ACTIVE_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "Failed":
            result = FAILED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "Blocked":
            result = BLOCKED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "BlockedRequiresOperatorAction":
            result = BLOCKEDREQUIRESOPERATORACTION_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        case "ManuallyBypassed":
            result = MANUALLYBYPASSED_ORGANIZATIONSWITCHOPTION_ACTIVATIONSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeOrganizationSwitchOption_activationStatus(values []OrganizationSwitchOption_activationStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i OrganizationSwitchOption_activationStatus) isMultiValue() bool {
    return false
}
