// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OutboundQueueItem struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Defines outbound delivery channels protected by delivery control.
    channel *OutboundDeliveryChannel
    // The id property
    id *string
    // The phoneNumber property
    phoneNumber *string
    // The reason property
    reason *string
    // Structured reason codes for outbound pacing and blocking decisions.
    reasonCode *OutboundQueueItem_reasonCode
    // The scheduledSendAt property
    scheduledSendAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Defines the source that requested outbound delivery.
    source *OutboundDeliverySource
    // Defines durable outbound delivery request statuses.
    status *OutboundDeliveryStatus
}
// NewOutboundQueueItem instantiates a new OutboundQueueItem and sets the default values.
func NewOutboundQueueItem()(*OutboundQueueItem) {
    m := &OutboundQueueItem{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOutboundQueueItemFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOutboundQueueItemFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOutboundQueueItem(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OutboundQueueItem) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetChannel gets the channel property value. Defines outbound delivery channels protected by delivery control.
// returns a *OutboundDeliveryChannel when successful
func (m *OutboundQueueItem) GetChannel()(*OutboundDeliveryChannel) {
    return m.channel
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OutboundQueueItem) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["channel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseOutboundDeliveryChannel)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChannel(val.(*OutboundDeliveryChannel))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["phoneNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhoneNumber(val)
        }
        return nil
    }
    res["reason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReason(val)
        }
        return nil
    }
    res["reasonCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseOutboundQueueItem_reasonCode)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReasonCode(val.(*OutboundQueueItem_reasonCode))
        }
        return nil
    }
    res["scheduledSendAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScheduledSendAt(val)
        }
        return nil
    }
    res["source"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseOutboundDeliverySource)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSource(val.(*OutboundDeliverySource))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseOutboundDeliveryStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*OutboundDeliveryStatus))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *OutboundQueueItem) GetId()(*string) {
    return m.id
}
// GetPhoneNumber gets the phoneNumber property value. The phoneNumber property
// returns a *string when successful
func (m *OutboundQueueItem) GetPhoneNumber()(*string) {
    return m.phoneNumber
}
// GetReason gets the reason property value. The reason property
// returns a *string when successful
func (m *OutboundQueueItem) GetReason()(*string) {
    return m.reason
}
// GetReasonCode gets the reasonCode property value. Structured reason codes for outbound pacing and blocking decisions.
// returns a *OutboundQueueItem_reasonCode when successful
func (m *OutboundQueueItem) GetReasonCode()(*OutboundQueueItem_reasonCode) {
    return m.reasonCode
}
// GetScheduledSendAt gets the scheduledSendAt property value. The scheduledSendAt property
// returns a *Time when successful
func (m *OutboundQueueItem) GetScheduledSendAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.scheduledSendAt
}
// GetSource gets the source property value. Defines the source that requested outbound delivery.
// returns a *OutboundDeliverySource when successful
func (m *OutboundQueueItem) GetSource()(*OutboundDeliverySource) {
    return m.source
}
// GetStatus gets the status property value. Defines durable outbound delivery request statuses.
// returns a *OutboundDeliveryStatus when successful
func (m *OutboundQueueItem) GetStatus()(*OutboundDeliveryStatus) {
    return m.status
}
// Serialize serializes information the current object
func (m *OutboundQueueItem) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetChannel() != nil {
        cast := (*m.GetChannel()).String()
        err := writer.WriteStringValue("channel", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("phoneNumber", m.GetPhoneNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("reason", m.GetReason())
        if err != nil {
            return err
        }
    }
    if m.GetReasonCode() != nil {
        cast := (*m.GetReasonCode()).String()
        err := writer.WriteStringValue("reasonCode", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("scheduledSendAt", m.GetScheduledSendAt())
        if err != nil {
            return err
        }
    }
    if m.GetSource() != nil {
        cast := (*m.GetSource()).String()
        err := writer.WriteStringValue("source", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OutboundQueueItem) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetChannel sets the channel property value. Defines outbound delivery channels protected by delivery control.
func (m *OutboundQueueItem) SetChannel(value *OutboundDeliveryChannel)() {
    m.channel = value
}
// SetId sets the id property value. The id property
func (m *OutboundQueueItem) SetId(value *string)() {
    m.id = value
}
// SetPhoneNumber sets the phoneNumber property value. The phoneNumber property
func (m *OutboundQueueItem) SetPhoneNumber(value *string)() {
    m.phoneNumber = value
}
// SetReason sets the reason property value. The reason property
func (m *OutboundQueueItem) SetReason(value *string)() {
    m.reason = value
}
// SetReasonCode sets the reasonCode property value. Structured reason codes for outbound pacing and blocking decisions.
func (m *OutboundQueueItem) SetReasonCode(value *OutboundQueueItem_reasonCode)() {
    m.reasonCode = value
}
// SetScheduledSendAt sets the scheduledSendAt property value. The scheduledSendAt property
func (m *OutboundQueueItem) SetScheduledSendAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.scheduledSendAt = value
}
// SetSource sets the source property value. Defines the source that requested outbound delivery.
func (m *OutboundQueueItem) SetSource(value *OutboundDeliverySource)() {
    m.source = value
}
// SetStatus sets the status property value. Defines durable outbound delivery request statuses.
func (m *OutboundQueueItem) SetStatus(value *OutboundDeliveryStatus)() {
    m.status = value
}
type OutboundQueueItemable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetChannel()(*OutboundDeliveryChannel)
    GetId()(*string)
    GetPhoneNumber()(*string)
    GetReason()(*string)
    GetReasonCode()(*OutboundQueueItem_reasonCode)
    GetScheduledSendAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetSource()(*OutboundDeliverySource)
    GetStatus()(*OutboundDeliveryStatus)
    SetChannel(value *OutboundDeliveryChannel)()
    SetId(value *string)()
    SetPhoneNumber(value *string)()
    SetReason(value *string)()
    SetReasonCode(value *OutboundQueueItem_reasonCode)()
    SetScheduledSendAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetSource(value *OutboundDeliverySource)()
    SetStatus(value *OutboundDeliveryStatus)()
}
