// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PhoneNumberStatusResponse_location public Leadping API schema for phone number location data.
type PhoneNumberStatusResponse_location struct {
	PhoneNumberLocation
}

// NewPhoneNumberStatusResponse_location instantiates a new PhoneNumberStatusResponse_location and sets the default values.
func NewPhoneNumberStatusResponse_location() *PhoneNumberStatusResponse_location {
	m := &PhoneNumberStatusResponse_location{
		PhoneNumberLocation: *NewPhoneNumberLocation(),
	}
	return m
}

// CreatePhoneNumberStatusResponse_locationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneNumberStatusResponse_locationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewPhoneNumberStatusResponse_location(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *PhoneNumberStatusResponse_location) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.PhoneNumberLocation.GetFieldDeserializers()
	return res
}

// Serialize serializes information the current object
func (m *PhoneNumberStatusResponse_location) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.PhoneNumberLocation.Serialize(writer)
	if err != nil {
		return err
	}
	return nil
}

type PhoneNumberStatusResponse_locationable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	PhoneNumberLocationable
}
