// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PhoneNumberResponse_location the location value for this phone number.
type PhoneNumberResponse_location struct {
    PhoneNumberLocation
}
// NewPhoneNumberResponse_location instantiates a new PhoneNumberResponse_location and sets the default values.
func NewPhoneNumberResponse_location()(*PhoneNumberResponse_location) {
    m := &PhoneNumberResponse_location{
        PhoneNumberLocation: *NewPhoneNumberLocation(),
    }
    return m
}
// CreatePhoneNumberResponse_locationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneNumberResponse_locationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPhoneNumberResponse_location(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PhoneNumberResponse_location) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.PhoneNumberLocation.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *PhoneNumberResponse_location) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.PhoneNumberLocation.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type PhoneNumberResponse_locationable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PhoneNumberLocationable
}
