// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PhoneLookup_portability complete portability data returned by Telnyx.
type PhoneLookup_portability struct {
    PhoneLookupPortability
}
// NewPhoneLookup_portability instantiates a new PhoneLookup_portability and sets the default values.
func NewPhoneLookup_portability()(*PhoneLookup_portability) {
    m := &PhoneLookup_portability{
        PhoneLookupPortability: *NewPhoneLookupPortability(),
    }
    return m
}
// CreatePhoneLookup_portabilityFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneLookup_portabilityFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPhoneLookup_portability(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PhoneLookup_portability) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.PhoneLookupPortability.GetFieldDeserializers()
    return res
}
// Serialize serializes information the current object
func (m *PhoneLookup_portability) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.PhoneLookupPortability.Serialize(writer)
    if err != nil {
        return err
    }
    return nil
}
type PhoneLookup_portabilityable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PhoneLookupPortabilityable
}
