// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PhoneNumberTableRow aPI DTO containing phone number data used by Leadping API contracts.
type PhoneNumberTableRow struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The admin force enablement override on this phone number.
    adminEnablementOverride PhoneNumberTableRow_adminEnablementOverrideable
    // The billing attribution value for this phone number.
    billingAttribution *string
    // The business value for this phone number.
    business *string
    // The capabilities value for this phone number.
    capabilities *string
    // Whether this phone number is enabled.
    enabled *bool
    // Defines the supported SMS Warmup Health State values.
    healthStatus *PhoneNumberTableRow_healthStatus
    // The unique ID for this phone number.
    id *string
    // Whether internal test only applies to this phone number.
    internalTestOnly *bool
    // The current inventory state for this phone number.
    inventoryState *PhoneNumberInventoryState
    // Whether this phone number is messaging program approved.
    isMessagingProgramApproved *bool
    // The location value for this phone number.
    location *string
    // The human-readable name shown for this phone number.
    name *string
    // The number value for this phone number.
    number *string
    // The ownership value for this phone number.
    ownership *string
    // The current provider lifecycle state for this phone number.
    providerLifecycleState *PhoneNumberProviderLifecycleState
    // The current provider reconciliation status for this phone number.
    providerReconciliationStatus *string
    // The current provider status for this phone number.
    providerStatus *string
    // The routing summary value for this phone number.
    routingSummary *string
    // Whether this phone number is SMS ready.
    smsReady *bool
    // The current status for this phone number.
    status *InternalPhoneNumberStatus
    // The 10DLC campaign ID associated with this phone number.
    tenDlcCampaignId *string
    // The current 10DLC campaign status for this phone number.
    tenDlcCampaignStatus *string
    // The type classification for this phone number.
    typeEscaped *string
    // The user value for this phone number.
    user *string
    // Whether this phone number is voice ready.
    voiceReady *bool
    // The warmup health score metric for this phone number.
    warmupHealthScore *int32
    // Whether warmup only applies to this phone number.
    warmupOnly *bool
    // The warmup progress percent metric for this phone number.
    warmupProgressPercent *int32
    // Defines the supported SMS Warmup Health State values.
    warmupState *PhoneNumberTableRow_warmupState
}
// NewPhoneNumberTableRow instantiates a new PhoneNumberTableRow and sets the default values.
func NewPhoneNumberTableRow()(*PhoneNumberTableRow) {
    m := &PhoneNumberTableRow{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePhoneNumberTableRowFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneNumberTableRowFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPhoneNumberTableRow(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PhoneNumberTableRow) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAdminEnablementOverride gets the adminEnablementOverride property value. The admin force enablement override on this phone number.
// returns a PhoneNumberTableRow_adminEnablementOverrideable when successful
func (m *PhoneNumberTableRow) GetAdminEnablementOverride()(PhoneNumberTableRow_adminEnablementOverrideable) {
    return m.adminEnablementOverride
}
// GetBillingAttribution gets the billingAttribution property value. The billing attribution value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetBillingAttribution()(*string) {
    return m.billingAttribution
}
// GetBusiness gets the business property value. The business value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetBusiness()(*string) {
    return m.business
}
// GetCapabilities gets the capabilities property value. The capabilities value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetCapabilities()(*string) {
    return m.capabilities
}
// GetEnabled gets the enabled property value. Whether this phone number is enabled.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PhoneNumberTableRow) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["adminEnablementOverride"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePhoneNumberTableRow_adminEnablementOverrideFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAdminEnablementOverride(val.(PhoneNumberTableRow_adminEnablementOverrideable))
        }
        return nil
    }
    res["billingAttribution"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBillingAttribution(val)
        }
        return nil
    }
    res["business"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBusiness(val)
        }
        return nil
    }
    res["capabilities"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCapabilities(val)
        }
        return nil
    }
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    res["healthStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePhoneNumberTableRow_healthStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHealthStatus(val.(*PhoneNumberTableRow_healthStatus))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["internalTestOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInternalTestOnly(val)
        }
        return nil
    }
    res["inventoryState"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePhoneNumberInventoryState)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInventoryState(val.(*PhoneNumberInventoryState))
        }
        return nil
    }
    res["isMessagingProgramApproved"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsMessagingProgramApproved(val)
        }
        return nil
    }
    res["location"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocation(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["number"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNumber(val)
        }
        return nil
    }
    res["ownership"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOwnership(val)
        }
        return nil
    }
    res["providerLifecycleState"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePhoneNumberProviderLifecycleState)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderLifecycleState(val.(*PhoneNumberProviderLifecycleState))
        }
        return nil
    }
    res["providerReconciliationStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderReconciliationStatus(val)
        }
        return nil
    }
    res["providerStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderStatus(val)
        }
        return nil
    }
    res["routingSummary"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoutingSummary(val)
        }
        return nil
    }
    res["smsReady"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSmsReady(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseInternalPhoneNumberStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*InternalPhoneNumberStatus))
        }
        return nil
    }
    res["tenDlcCampaignId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTenDlcCampaignId(val)
        }
        return nil
    }
    res["tenDlcCampaignStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTenDlcCampaignStatus(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    res["user"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUser(val)
        }
        return nil
    }
    res["voiceReady"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVoiceReady(val)
        }
        return nil
    }
    res["warmupHealthScore"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWarmupHealthScore(val)
        }
        return nil
    }
    res["warmupOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWarmupOnly(val)
        }
        return nil
    }
    res["warmupProgressPercent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWarmupProgressPercent(val)
        }
        return nil
    }
    res["warmupState"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePhoneNumberTableRow_warmupState)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWarmupState(val.(*PhoneNumberTableRow_warmupState))
        }
        return nil
    }
    return res
}
// GetHealthStatus gets the healthStatus property value. Defines the supported SMS Warmup Health State values.
// returns a *PhoneNumberTableRow_healthStatus when successful
func (m *PhoneNumberTableRow) GetHealthStatus()(*PhoneNumberTableRow_healthStatus) {
    return m.healthStatus
}
// GetId gets the id property value. The unique ID for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetId()(*string) {
    return m.id
}
// GetInternalTestOnly gets the internalTestOnly property value. Whether internal test only applies to this phone number.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetInternalTestOnly()(*bool) {
    return m.internalTestOnly
}
// GetInventoryState gets the inventoryState property value. The current inventory state for this phone number.
// returns a *PhoneNumberInventoryState when successful
func (m *PhoneNumberTableRow) GetInventoryState()(*PhoneNumberInventoryState) {
    return m.inventoryState
}
// GetIsMessagingProgramApproved gets the isMessagingProgramApproved property value. Whether this phone number is messaging program approved.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetIsMessagingProgramApproved()(*bool) {
    return m.isMessagingProgramApproved
}
// GetLocation gets the location property value. The location value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetLocation()(*string) {
    return m.location
}
// GetName gets the name property value. The human-readable name shown for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetName()(*string) {
    return m.name
}
// GetNumber gets the number property value. The number value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetNumber()(*string) {
    return m.number
}
// GetOwnership gets the ownership property value. The ownership value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetOwnership()(*string) {
    return m.ownership
}
// GetProviderLifecycleState gets the providerLifecycleState property value. The current provider lifecycle state for this phone number.
// returns a *PhoneNumberProviderLifecycleState when successful
func (m *PhoneNumberTableRow) GetProviderLifecycleState()(*PhoneNumberProviderLifecycleState) {
    return m.providerLifecycleState
}
// GetProviderReconciliationStatus gets the providerReconciliationStatus property value. The current provider reconciliation status for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetProviderReconciliationStatus()(*string) {
    return m.providerReconciliationStatus
}
// GetProviderStatus gets the providerStatus property value. The current provider status for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetProviderStatus()(*string) {
    return m.providerStatus
}
// GetRoutingSummary gets the routingSummary property value. The routing summary value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetRoutingSummary()(*string) {
    return m.routingSummary
}
// GetSmsReady gets the smsReady property value. Whether this phone number is SMS ready.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetSmsReady()(*bool) {
    return m.smsReady
}
// GetStatus gets the status property value. The current status for this phone number.
// returns a *InternalPhoneNumberStatus when successful
func (m *PhoneNumberTableRow) GetStatus()(*InternalPhoneNumberStatus) {
    return m.status
}
// GetTenDlcCampaignId gets the tenDlcCampaignId property value. The 10DLC campaign ID associated with this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetTenDlcCampaignId()(*string) {
    return m.tenDlcCampaignId
}
// GetTenDlcCampaignStatus gets the tenDlcCampaignStatus property value. The current 10DLC campaign status for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetTenDlcCampaignStatus()(*string) {
    return m.tenDlcCampaignStatus
}
// GetTypeEscaped gets the type property value. The type classification for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetTypeEscaped()(*string) {
    return m.typeEscaped
}
// GetUser gets the user property value. The user value for this phone number.
// returns a *string when successful
func (m *PhoneNumberTableRow) GetUser()(*string) {
    return m.user
}
// GetVoiceReady gets the voiceReady property value. Whether this phone number is voice ready.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetVoiceReady()(*bool) {
    return m.voiceReady
}
// GetWarmupHealthScore gets the warmupHealthScore property value. The warmup health score metric for this phone number.
// returns a *int32 when successful
func (m *PhoneNumberTableRow) GetWarmupHealthScore()(*int32) {
    return m.warmupHealthScore
}
// GetWarmupOnly gets the warmupOnly property value. Whether warmup only applies to this phone number.
// returns a *bool when successful
func (m *PhoneNumberTableRow) GetWarmupOnly()(*bool) {
    return m.warmupOnly
}
// GetWarmupProgressPercent gets the warmupProgressPercent property value. The warmup progress percent metric for this phone number.
// returns a *int32 when successful
func (m *PhoneNumberTableRow) GetWarmupProgressPercent()(*int32) {
    return m.warmupProgressPercent
}
// GetWarmupState gets the warmupState property value. Defines the supported SMS Warmup Health State values.
// returns a *PhoneNumberTableRow_warmupState when successful
func (m *PhoneNumberTableRow) GetWarmupState()(*PhoneNumberTableRow_warmupState) {
    return m.warmupState
}
// Serialize serializes information the current object
func (m *PhoneNumberTableRow) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("adminEnablementOverride", m.GetAdminEnablementOverride())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("billingAttribution", m.GetBillingAttribution())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("business", m.GetBusiness())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("capabilities", m.GetCapabilities())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    if m.GetHealthStatus() != nil {
        cast := (*m.GetHealthStatus()).String()
        err := writer.WriteStringValue("healthStatus", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("internalTestOnly", m.GetInternalTestOnly())
        if err != nil {
            return err
        }
    }
    if m.GetInventoryState() != nil {
        cast := (*m.GetInventoryState()).String()
        err := writer.WriteStringValue("inventoryState", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isMessagingProgramApproved", m.GetIsMessagingProgramApproved())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("location", m.GetLocation())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("number", m.GetNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ownership", m.GetOwnership())
        if err != nil {
            return err
        }
    }
    if m.GetProviderLifecycleState() != nil {
        cast := (*m.GetProviderLifecycleState()).String()
        err := writer.WriteStringValue("providerLifecycleState", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("providerReconciliationStatus", m.GetProviderReconciliationStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("providerStatus", m.GetProviderStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("routingSummary", m.GetRoutingSummary())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("smsReady", m.GetSmsReady())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tenDlcCampaignId", m.GetTenDlcCampaignId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tenDlcCampaignStatus", m.GetTenDlcCampaignStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("user", m.GetUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("voiceReady", m.GetVoiceReady())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("warmupHealthScore", m.GetWarmupHealthScore())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("warmupOnly", m.GetWarmupOnly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("warmupProgressPercent", m.GetWarmupProgressPercent())
        if err != nil {
            return err
        }
    }
    if m.GetWarmupState() != nil {
        cast := (*m.GetWarmupState()).String()
        err := writer.WriteStringValue("warmupState", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PhoneNumberTableRow) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAdminEnablementOverride sets the adminEnablementOverride property value. The admin force enablement override on this phone number.
func (m *PhoneNumberTableRow) SetAdminEnablementOverride(value PhoneNumberTableRow_adminEnablementOverrideable)() {
    m.adminEnablementOverride = value
}
// SetBillingAttribution sets the billingAttribution property value. The billing attribution value for this phone number.
func (m *PhoneNumberTableRow) SetBillingAttribution(value *string)() {
    m.billingAttribution = value
}
// SetBusiness sets the business property value. The business value for this phone number.
func (m *PhoneNumberTableRow) SetBusiness(value *string)() {
    m.business = value
}
// SetCapabilities sets the capabilities property value. The capabilities value for this phone number.
func (m *PhoneNumberTableRow) SetCapabilities(value *string)() {
    m.capabilities = value
}
// SetEnabled sets the enabled property value. Whether this phone number is enabled.
func (m *PhoneNumberTableRow) SetEnabled(value *bool)() {
    m.enabled = value
}
// SetHealthStatus sets the healthStatus property value. Defines the supported SMS Warmup Health State values.
func (m *PhoneNumberTableRow) SetHealthStatus(value *PhoneNumberTableRow_healthStatus)() {
    m.healthStatus = value
}
// SetId sets the id property value. The unique ID for this phone number.
func (m *PhoneNumberTableRow) SetId(value *string)() {
    m.id = value
}
// SetInternalTestOnly sets the internalTestOnly property value. Whether internal test only applies to this phone number.
func (m *PhoneNumberTableRow) SetInternalTestOnly(value *bool)() {
    m.internalTestOnly = value
}
// SetInventoryState sets the inventoryState property value. The current inventory state for this phone number.
func (m *PhoneNumberTableRow) SetInventoryState(value *PhoneNumberInventoryState)() {
    m.inventoryState = value
}
// SetIsMessagingProgramApproved sets the isMessagingProgramApproved property value. Whether this phone number is messaging program approved.
func (m *PhoneNumberTableRow) SetIsMessagingProgramApproved(value *bool)() {
    m.isMessagingProgramApproved = value
}
// SetLocation sets the location property value. The location value for this phone number.
func (m *PhoneNumberTableRow) SetLocation(value *string)() {
    m.location = value
}
// SetName sets the name property value. The human-readable name shown for this phone number.
func (m *PhoneNumberTableRow) SetName(value *string)() {
    m.name = value
}
// SetNumber sets the number property value. The number value for this phone number.
func (m *PhoneNumberTableRow) SetNumber(value *string)() {
    m.number = value
}
// SetOwnership sets the ownership property value. The ownership value for this phone number.
func (m *PhoneNumberTableRow) SetOwnership(value *string)() {
    m.ownership = value
}
// SetProviderLifecycleState sets the providerLifecycleState property value. The current provider lifecycle state for this phone number.
func (m *PhoneNumberTableRow) SetProviderLifecycleState(value *PhoneNumberProviderLifecycleState)() {
    m.providerLifecycleState = value
}
// SetProviderReconciliationStatus sets the providerReconciliationStatus property value. The current provider reconciliation status for this phone number.
func (m *PhoneNumberTableRow) SetProviderReconciliationStatus(value *string)() {
    m.providerReconciliationStatus = value
}
// SetProviderStatus sets the providerStatus property value. The current provider status for this phone number.
func (m *PhoneNumberTableRow) SetProviderStatus(value *string)() {
    m.providerStatus = value
}
// SetRoutingSummary sets the routingSummary property value. The routing summary value for this phone number.
func (m *PhoneNumberTableRow) SetRoutingSummary(value *string)() {
    m.routingSummary = value
}
// SetSmsReady sets the smsReady property value. Whether this phone number is SMS ready.
func (m *PhoneNumberTableRow) SetSmsReady(value *bool)() {
    m.smsReady = value
}
// SetStatus sets the status property value. The current status for this phone number.
func (m *PhoneNumberTableRow) SetStatus(value *InternalPhoneNumberStatus)() {
    m.status = value
}
// SetTenDlcCampaignId sets the tenDlcCampaignId property value. The 10DLC campaign ID associated with this phone number.
func (m *PhoneNumberTableRow) SetTenDlcCampaignId(value *string)() {
    m.tenDlcCampaignId = value
}
// SetTenDlcCampaignStatus sets the tenDlcCampaignStatus property value. The current 10DLC campaign status for this phone number.
func (m *PhoneNumberTableRow) SetTenDlcCampaignStatus(value *string)() {
    m.tenDlcCampaignStatus = value
}
// SetTypeEscaped sets the type property value. The type classification for this phone number.
func (m *PhoneNumberTableRow) SetTypeEscaped(value *string)() {
    m.typeEscaped = value
}
// SetUser sets the user property value. The user value for this phone number.
func (m *PhoneNumberTableRow) SetUser(value *string)() {
    m.user = value
}
// SetVoiceReady sets the voiceReady property value. Whether this phone number is voice ready.
func (m *PhoneNumberTableRow) SetVoiceReady(value *bool)() {
    m.voiceReady = value
}
// SetWarmupHealthScore sets the warmupHealthScore property value. The warmup health score metric for this phone number.
func (m *PhoneNumberTableRow) SetWarmupHealthScore(value *int32)() {
    m.warmupHealthScore = value
}
// SetWarmupOnly sets the warmupOnly property value. Whether warmup only applies to this phone number.
func (m *PhoneNumberTableRow) SetWarmupOnly(value *bool)() {
    m.warmupOnly = value
}
// SetWarmupProgressPercent sets the warmupProgressPercent property value. The warmup progress percent metric for this phone number.
func (m *PhoneNumberTableRow) SetWarmupProgressPercent(value *int32)() {
    m.warmupProgressPercent = value
}
// SetWarmupState sets the warmupState property value. Defines the supported SMS Warmup Health State values.
func (m *PhoneNumberTableRow) SetWarmupState(value *PhoneNumberTableRow_warmupState)() {
    m.warmupState = value
}
type PhoneNumberTableRowable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAdminEnablementOverride()(PhoneNumberTableRow_adminEnablementOverrideable)
    GetBillingAttribution()(*string)
    GetBusiness()(*string)
    GetCapabilities()(*string)
    GetEnabled()(*bool)
    GetHealthStatus()(*PhoneNumberTableRow_healthStatus)
    GetId()(*string)
    GetInternalTestOnly()(*bool)
    GetInventoryState()(*PhoneNumberInventoryState)
    GetIsMessagingProgramApproved()(*bool)
    GetLocation()(*string)
    GetName()(*string)
    GetNumber()(*string)
    GetOwnership()(*string)
    GetProviderLifecycleState()(*PhoneNumberProviderLifecycleState)
    GetProviderReconciliationStatus()(*string)
    GetProviderStatus()(*string)
    GetRoutingSummary()(*string)
    GetSmsReady()(*bool)
    GetStatus()(*InternalPhoneNumberStatus)
    GetTenDlcCampaignId()(*string)
    GetTenDlcCampaignStatus()(*string)
    GetTypeEscaped()(*string)
    GetUser()(*string)
    GetVoiceReady()(*bool)
    GetWarmupHealthScore()(*int32)
    GetWarmupOnly()(*bool)
    GetWarmupProgressPercent()(*int32)
    GetWarmupState()(*PhoneNumberTableRow_warmupState)
    SetAdminEnablementOverride(value PhoneNumberTableRow_adminEnablementOverrideable)()
    SetBillingAttribution(value *string)()
    SetBusiness(value *string)()
    SetCapabilities(value *string)()
    SetEnabled(value *bool)()
    SetHealthStatus(value *PhoneNumberTableRow_healthStatus)()
    SetId(value *string)()
    SetInternalTestOnly(value *bool)()
    SetInventoryState(value *PhoneNumberInventoryState)()
    SetIsMessagingProgramApproved(value *bool)()
    SetLocation(value *string)()
    SetName(value *string)()
    SetNumber(value *string)()
    SetOwnership(value *string)()
    SetProviderLifecycleState(value *PhoneNumberProviderLifecycleState)()
    SetProviderReconciliationStatus(value *string)()
    SetProviderStatus(value *string)()
    SetRoutingSummary(value *string)()
    SetSmsReady(value *bool)()
    SetStatus(value *InternalPhoneNumberStatus)()
    SetTenDlcCampaignId(value *string)()
    SetTenDlcCampaignStatus(value *string)()
    SetTypeEscaped(value *string)()
    SetUser(value *string)()
    SetVoiceReady(value *bool)()
    SetWarmupHealthScore(value *int32)()
    SetWarmupOnly(value *bool)()
    SetWarmupProgressPercent(value *int32)()
    SetWarmupState(value *PhoneNumberTableRow_warmupState)()
}
