// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PhoneNumberRoutingMetadata aPI DTO containing phone number routing metadata data used by Leadping API contracts.
type PhoneNumberRoutingMetadata struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The campaign ID associated with this phone number routing metadata.
    campaignId *string
    // Whether internal test only applies to this phone number routing metadata.
    internalTestOnly *bool
    // The messaging profile ID associated with this phone number routing metadata.
    messagingProfileId *string
    // Whether SMS is enabled for this phone number routing metadata.
    smsEnabled *bool
    // The source ID associated with this phone number routing metadata.
    sourceId *string
    // The team ID associated with this phone number routing metadata.
    teamId *string
    // The voice connection ID associated with this phone number routing metadata.
    voiceConnectionId *string
    // Whether voice is enabled for this phone number routing metadata.
    voiceEnabled *bool
    // Whether warmup only applies to this phone number routing metadata.
    warmupOnly *bool
}
// NewPhoneNumberRoutingMetadata instantiates a new PhoneNumberRoutingMetadata and sets the default values.
func NewPhoneNumberRoutingMetadata()(*PhoneNumberRoutingMetadata) {
    m := &PhoneNumberRoutingMetadata{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePhoneNumberRoutingMetadataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneNumberRoutingMetadataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPhoneNumberRoutingMetadata(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PhoneNumberRoutingMetadata) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCampaignId gets the campaignId property value. The campaign ID associated with this phone number routing metadata.
// returns a *string when successful
func (m *PhoneNumberRoutingMetadata) GetCampaignId()(*string) {
    return m.campaignId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PhoneNumberRoutingMetadata) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["campaignId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCampaignId(val)
        }
        return nil
    }
    res["internalTestOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInternalTestOnly(val)
        }
        return nil
    }
    res["messagingProfileId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessagingProfileId(val)
        }
        return nil
    }
    res["smsEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSmsEnabled(val)
        }
        return nil
    }
    res["sourceId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSourceId(val)
        }
        return nil
    }
    res["teamId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTeamId(val)
        }
        return nil
    }
    res["voiceConnectionId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVoiceConnectionId(val)
        }
        return nil
    }
    res["voiceEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVoiceEnabled(val)
        }
        return nil
    }
    res["warmupOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWarmupOnly(val)
        }
        return nil
    }
    return res
}
// GetInternalTestOnly gets the internalTestOnly property value. Whether internal test only applies to this phone number routing metadata.
// returns a *bool when successful
func (m *PhoneNumberRoutingMetadata) GetInternalTestOnly()(*bool) {
    return m.internalTestOnly
}
// GetMessagingProfileId gets the messagingProfileId property value. The messaging profile ID associated with this phone number routing metadata.
// returns a *string when successful
func (m *PhoneNumberRoutingMetadata) GetMessagingProfileId()(*string) {
    return m.messagingProfileId
}
// GetSmsEnabled gets the smsEnabled property value. Whether SMS is enabled for this phone number routing metadata.
// returns a *bool when successful
func (m *PhoneNumberRoutingMetadata) GetSmsEnabled()(*bool) {
    return m.smsEnabled
}
// GetSourceId gets the sourceId property value. The source ID associated with this phone number routing metadata.
// returns a *string when successful
func (m *PhoneNumberRoutingMetadata) GetSourceId()(*string) {
    return m.sourceId
}
// GetTeamId gets the teamId property value. The team ID associated with this phone number routing metadata.
// returns a *string when successful
func (m *PhoneNumberRoutingMetadata) GetTeamId()(*string) {
    return m.teamId
}
// GetVoiceConnectionId gets the voiceConnectionId property value. The voice connection ID associated with this phone number routing metadata.
// returns a *string when successful
func (m *PhoneNumberRoutingMetadata) GetVoiceConnectionId()(*string) {
    return m.voiceConnectionId
}
// GetVoiceEnabled gets the voiceEnabled property value. Whether voice is enabled for this phone number routing metadata.
// returns a *bool when successful
func (m *PhoneNumberRoutingMetadata) GetVoiceEnabled()(*bool) {
    return m.voiceEnabled
}
// GetWarmupOnly gets the warmupOnly property value. Whether warmup only applies to this phone number routing metadata.
// returns a *bool when successful
func (m *PhoneNumberRoutingMetadata) GetWarmupOnly()(*bool) {
    return m.warmupOnly
}
// Serialize serializes information the current object
func (m *PhoneNumberRoutingMetadata) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("campaignId", m.GetCampaignId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("internalTestOnly", m.GetInternalTestOnly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("messagingProfileId", m.GetMessagingProfileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("smsEnabled", m.GetSmsEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("sourceId", m.GetSourceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("teamId", m.GetTeamId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("voiceConnectionId", m.GetVoiceConnectionId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("voiceEnabled", m.GetVoiceEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("warmupOnly", m.GetWarmupOnly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PhoneNumberRoutingMetadata) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCampaignId sets the campaignId property value. The campaign ID associated with this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetCampaignId(value *string)() {
    m.campaignId = value
}
// SetInternalTestOnly sets the internalTestOnly property value. Whether internal test only applies to this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetInternalTestOnly(value *bool)() {
    m.internalTestOnly = value
}
// SetMessagingProfileId sets the messagingProfileId property value. The messaging profile ID associated with this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetMessagingProfileId(value *string)() {
    m.messagingProfileId = value
}
// SetSmsEnabled sets the smsEnabled property value. Whether SMS is enabled for this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetSmsEnabled(value *bool)() {
    m.smsEnabled = value
}
// SetSourceId sets the sourceId property value. The source ID associated with this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetSourceId(value *string)() {
    m.sourceId = value
}
// SetTeamId sets the teamId property value. The team ID associated with this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetTeamId(value *string)() {
    m.teamId = value
}
// SetVoiceConnectionId sets the voiceConnectionId property value. The voice connection ID associated with this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetVoiceConnectionId(value *string)() {
    m.voiceConnectionId = value
}
// SetVoiceEnabled sets the voiceEnabled property value. Whether voice is enabled for this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetVoiceEnabled(value *bool)() {
    m.voiceEnabled = value
}
// SetWarmupOnly sets the warmupOnly property value. Whether warmup only applies to this phone number routing metadata.
func (m *PhoneNumberRoutingMetadata) SetWarmupOnly(value *bool)() {
    m.warmupOnly = value
}
type PhoneNumberRoutingMetadataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCampaignId()(*string)
    GetInternalTestOnly()(*bool)
    GetMessagingProfileId()(*string)
    GetSmsEnabled()(*bool)
    GetSourceId()(*string)
    GetTeamId()(*string)
    GetVoiceConnectionId()(*string)
    GetVoiceEnabled()(*bool)
    GetWarmupOnly()(*bool)
    SetCampaignId(value *string)()
    SetInternalTestOnly(value *bool)()
    SetMessagingProfileId(value *string)()
    SetSmsEnabled(value *bool)()
    SetSourceId(value *string)()
    SetTeamId(value *string)()
    SetVoiceConnectionId(value *string)()
    SetVoiceEnabled(value *bool)()
    SetWarmupOnly(value *bool)()
}
