// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SuppressionEntryRequest request payload for suppression entry.
type SuppressionEntryRequest struct {
    // The actor ID associated with this ion entry.
    actorId *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The business ID associated with this ion entry.
    businessId *string
    // The channel value for this ion entry.
    channel *string
    // The email address associated with this ion entry.
    email *string
    // The phone number associated with this ion entry.
    phoneNumber *string
    // The provider event ID associated with this ion entry.
    providerEventId *string
    // The human-readable reason explaining this ion entry.
    reason *string
    // The recipient identifier value for this ion entry.
    recipientIdentifier *string
    // The safe metadata key-value data carried with this ion entry; values must be safe to expose in API responses.
    safeMetadata SuppressionEntryRequest_safeMetadataable
    // The source value for this ion entry.
    source *string
    // The source event ID associated with this ion entry.
    sourceEventId *string
    // The date and time for the timestamp value on this ion entry.
    timestamp *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// NewSuppressionEntryRequest instantiates a new SuppressionEntryRequest and sets the default values.
func NewSuppressionEntryRequest()(*SuppressionEntryRequest) {
    m := &SuppressionEntryRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSuppressionEntryRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSuppressionEntryRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSuppressionEntryRequest(), nil
}
// GetActorId gets the actorId property value. The actor ID associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetActorId()(*string) {
    return m.actorId
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SuppressionEntryRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBusinessId gets the businessId property value. The business ID associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetBusinessId()(*string) {
    return m.businessId
}
// GetChannel gets the channel property value. The channel value for this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetChannel()(*string) {
    return m.channel
}
// GetEmail gets the email property value. The email address associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetEmail()(*string) {
    return m.email
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SuppressionEntryRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["actorId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActorId(val)
        }
        return nil
    }
    res["businessId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBusinessId(val)
        }
        return nil
    }
    res["channel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChannel(val)
        }
        return nil
    }
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["phoneNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhoneNumber(val)
        }
        return nil
    }
    res["providerEventId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderEventId(val)
        }
        return nil
    }
    res["reason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReason(val)
        }
        return nil
    }
    res["recipientIdentifier"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRecipientIdentifier(val)
        }
        return nil
    }
    res["safeMetadata"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSuppressionEntryRequest_safeMetadataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSafeMetadata(val.(SuppressionEntryRequest_safeMetadataable))
        }
        return nil
    }
    res["source"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSource(val)
        }
        return nil
    }
    res["sourceEventId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSourceEventId(val)
        }
        return nil
    }
    res["timestamp"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTimestamp(val)
        }
        return nil
    }
    return res
}
// GetPhoneNumber gets the phoneNumber property value. The phone number associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetPhoneNumber()(*string) {
    return m.phoneNumber
}
// GetProviderEventId gets the providerEventId property value. The provider event ID associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetProviderEventId()(*string) {
    return m.providerEventId
}
// GetReason gets the reason property value. The human-readable reason explaining this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetReason()(*string) {
    return m.reason
}
// GetRecipientIdentifier gets the recipientIdentifier property value. The recipient identifier value for this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetRecipientIdentifier()(*string) {
    return m.recipientIdentifier
}
// GetSafeMetadata gets the safeMetadata property value. The safe metadata key-value data carried with this ion entry; values must be safe to expose in API responses.
// returns a SuppressionEntryRequest_safeMetadataable when successful
func (m *SuppressionEntryRequest) GetSafeMetadata()(SuppressionEntryRequest_safeMetadataable) {
    return m.safeMetadata
}
// GetSource gets the source property value. The source value for this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetSource()(*string) {
    return m.source
}
// GetSourceEventId gets the sourceEventId property value. The source event ID associated with this ion entry.
// returns a *string when successful
func (m *SuppressionEntryRequest) GetSourceEventId()(*string) {
    return m.sourceEventId
}
// GetTimestamp gets the timestamp property value. The date and time for the timestamp value on this ion entry.
// returns a *Time when successful
func (m *SuppressionEntryRequest) GetTimestamp()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.timestamp
}
// Serialize serializes information the current object
func (m *SuppressionEntryRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("actorId", m.GetActorId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("businessId", m.GetBusinessId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("channel", m.GetChannel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("phoneNumber", m.GetPhoneNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("providerEventId", m.GetProviderEventId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("reason", m.GetReason())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("recipientIdentifier", m.GetRecipientIdentifier())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("safeMetadata", m.GetSafeMetadata())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("source", m.GetSource())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("sourceEventId", m.GetSourceEventId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("timestamp", m.GetTimestamp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActorId sets the actorId property value. The actor ID associated with this ion entry.
func (m *SuppressionEntryRequest) SetActorId(value *string)() {
    m.actorId = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SuppressionEntryRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBusinessId sets the businessId property value. The business ID associated with this ion entry.
func (m *SuppressionEntryRequest) SetBusinessId(value *string)() {
    m.businessId = value
}
// SetChannel sets the channel property value. The channel value for this ion entry.
func (m *SuppressionEntryRequest) SetChannel(value *string)() {
    m.channel = value
}
// SetEmail sets the email property value. The email address associated with this ion entry.
func (m *SuppressionEntryRequest) SetEmail(value *string)() {
    m.email = value
}
// SetPhoneNumber sets the phoneNumber property value. The phone number associated with this ion entry.
func (m *SuppressionEntryRequest) SetPhoneNumber(value *string)() {
    m.phoneNumber = value
}
// SetProviderEventId sets the providerEventId property value. The provider event ID associated with this ion entry.
func (m *SuppressionEntryRequest) SetProviderEventId(value *string)() {
    m.providerEventId = value
}
// SetReason sets the reason property value. The human-readable reason explaining this ion entry.
func (m *SuppressionEntryRequest) SetReason(value *string)() {
    m.reason = value
}
// SetRecipientIdentifier sets the recipientIdentifier property value. The recipient identifier value for this ion entry.
func (m *SuppressionEntryRequest) SetRecipientIdentifier(value *string)() {
    m.recipientIdentifier = value
}
// SetSafeMetadata sets the safeMetadata property value. The safe metadata key-value data carried with this ion entry; values must be safe to expose in API responses.
func (m *SuppressionEntryRequest) SetSafeMetadata(value SuppressionEntryRequest_safeMetadataable)() {
    m.safeMetadata = value
}
// SetSource sets the source property value. The source value for this ion entry.
func (m *SuppressionEntryRequest) SetSource(value *string)() {
    m.source = value
}
// SetSourceEventId sets the sourceEventId property value. The source event ID associated with this ion entry.
func (m *SuppressionEntryRequest) SetSourceEventId(value *string)() {
    m.sourceEventId = value
}
// SetTimestamp sets the timestamp property value. The date and time for the timestamp value on this ion entry.
func (m *SuppressionEntryRequest) SetTimestamp(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.timestamp = value
}
type SuppressionEntryRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActorId()(*string)
    GetBusinessId()(*string)
    GetChannel()(*string)
    GetEmail()(*string)
    GetPhoneNumber()(*string)
    GetProviderEventId()(*string)
    GetReason()(*string)
    GetRecipientIdentifier()(*string)
    GetSafeMetadata()(SuppressionEntryRequest_safeMetadataable)
    GetSource()(*string)
    GetSourceEventId()(*string)
    GetTimestamp()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetActorId(value *string)()
    SetBusinessId(value *string)()
    SetChannel(value *string)()
    SetEmail(value *string)()
    SetPhoneNumber(value *string)()
    SetProviderEventId(value *string)()
    SetReason(value *string)()
    SetRecipientIdentifier(value *string)()
    SetSafeMetadata(value SuppressionEntryRequest_safeMetadataable)()
    SetSource(value *string)()
    SetSourceEventId(value *string)()
    SetTimestamp(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
