// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// UserNotificationPreferences aPI DTO containing user notification preferences data used by Leadping API contracts.
type UserNotificationPreferences struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Whether automation failed notifications are enabled for this user notification preferences.
    automationFailedEnabled *bool
    // Whether billing email is enabled for this user notification preferences.
    billingEmailEnabled *bool
    // Whether billing SMS is enabled for this user notification preferences.
    billingSmsEnabled *bool
    // Whether low wallet balance notifications are enabled for this user notification preferences.
    lowWalletBalanceEnabled *bool
    // Whether missed call notifications are enabled for this user notification preferences.
    missedCallEnabled *bool
    // Whether new lead email is enabled for this user notification preferences.
    newLeadEmailEnabled *bool
    // Whether new lead notifications are enabled for this user notification preferences.
    newLeadEnabled *bool
    // Whether new lead SMS is enabled for this user notification preferences.
    newLeadSmsEnabled *bool
    // Whether payment failed notifications are enabled for this user notification preferences.
    paymentFailedEnabled *bool
    // Whether subscription renewing notifications are enabled for this user notification preferences.
    subscriptionRenewingEnabled *bool
    // Whether 10DLC status notifications are enabled for this user notification preferences.
    tenDlcStatusEnabled *bool
    // Whether unread SMS notifications are enabled for this user notification preferences.
    unreadSmsEnabled *bool
    // Whether usage limit hit notifications are enabled for this user notification preferences.
    usageLimitHitEnabled *bool
}
// NewUserNotificationPreferences instantiates a new UserNotificationPreferences and sets the default values.
func NewUserNotificationPreferences()(*UserNotificationPreferences) {
    m := &UserNotificationPreferences{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUserNotificationPreferencesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserNotificationPreferencesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUserNotificationPreferences(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UserNotificationPreferences) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAutomationFailedEnabled gets the automationFailedEnabled property value. Whether automation failed notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetAutomationFailedEnabled()(*bool) {
    return m.automationFailedEnabled
}
// GetBillingEmailEnabled gets the billingEmailEnabled property value. Whether billing email is enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetBillingEmailEnabled()(*bool) {
    return m.billingEmailEnabled
}
// GetBillingSmsEnabled gets the billingSmsEnabled property value. Whether billing SMS is enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetBillingSmsEnabled()(*bool) {
    return m.billingSmsEnabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UserNotificationPreferences) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["automationFailedEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutomationFailedEnabled(val)
        }
        return nil
    }
    res["billingEmailEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBillingEmailEnabled(val)
        }
        return nil
    }
    res["billingSmsEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBillingSmsEnabled(val)
        }
        return nil
    }
    res["lowWalletBalanceEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLowWalletBalanceEnabled(val)
        }
        return nil
    }
    res["missedCallEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMissedCallEnabled(val)
        }
        return nil
    }
    res["newLeadEmailEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNewLeadEmailEnabled(val)
        }
        return nil
    }
    res["newLeadEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNewLeadEnabled(val)
        }
        return nil
    }
    res["newLeadSmsEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNewLeadSmsEnabled(val)
        }
        return nil
    }
    res["paymentFailedEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPaymentFailedEnabled(val)
        }
        return nil
    }
    res["subscriptionRenewingEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubscriptionRenewingEnabled(val)
        }
        return nil
    }
    res["tenDlcStatusEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTenDlcStatusEnabled(val)
        }
        return nil
    }
    res["unreadSmsEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUnreadSmsEnabled(val)
        }
        return nil
    }
    res["usageLimitHitEnabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUsageLimitHitEnabled(val)
        }
        return nil
    }
    return res
}
// GetLowWalletBalanceEnabled gets the lowWalletBalanceEnabled property value. Whether low wallet balance notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetLowWalletBalanceEnabled()(*bool) {
    return m.lowWalletBalanceEnabled
}
// GetMissedCallEnabled gets the missedCallEnabled property value. Whether missed call notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetMissedCallEnabled()(*bool) {
    return m.missedCallEnabled
}
// GetNewLeadEmailEnabled gets the newLeadEmailEnabled property value. Whether new lead email is enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetNewLeadEmailEnabled()(*bool) {
    return m.newLeadEmailEnabled
}
// GetNewLeadEnabled gets the newLeadEnabled property value. Whether new lead notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetNewLeadEnabled()(*bool) {
    return m.newLeadEnabled
}
// GetNewLeadSmsEnabled gets the newLeadSmsEnabled property value. Whether new lead SMS is enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetNewLeadSmsEnabled()(*bool) {
    return m.newLeadSmsEnabled
}
// GetPaymentFailedEnabled gets the paymentFailedEnabled property value. Whether payment failed notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetPaymentFailedEnabled()(*bool) {
    return m.paymentFailedEnabled
}
// GetSubscriptionRenewingEnabled gets the subscriptionRenewingEnabled property value. Whether subscription renewing notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetSubscriptionRenewingEnabled()(*bool) {
    return m.subscriptionRenewingEnabled
}
// GetTenDlcStatusEnabled gets the tenDlcStatusEnabled property value. Whether 10DLC status notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetTenDlcStatusEnabled()(*bool) {
    return m.tenDlcStatusEnabled
}
// GetUnreadSmsEnabled gets the unreadSmsEnabled property value. Whether unread SMS notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetUnreadSmsEnabled()(*bool) {
    return m.unreadSmsEnabled
}
// GetUsageLimitHitEnabled gets the usageLimitHitEnabled property value. Whether usage limit hit notifications are enabled for this user notification preferences.
// returns a *bool when successful
func (m *UserNotificationPreferences) GetUsageLimitHitEnabled()(*bool) {
    return m.usageLimitHitEnabled
}
// Serialize serializes information the current object
func (m *UserNotificationPreferences) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("automationFailedEnabled", m.GetAutomationFailedEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("billingEmailEnabled", m.GetBillingEmailEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("billingSmsEnabled", m.GetBillingSmsEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("lowWalletBalanceEnabled", m.GetLowWalletBalanceEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("missedCallEnabled", m.GetMissedCallEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("newLeadEmailEnabled", m.GetNewLeadEmailEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("newLeadEnabled", m.GetNewLeadEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("newLeadSmsEnabled", m.GetNewLeadSmsEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("paymentFailedEnabled", m.GetPaymentFailedEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("subscriptionRenewingEnabled", m.GetSubscriptionRenewingEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("tenDlcStatusEnabled", m.GetTenDlcStatusEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("unreadSmsEnabled", m.GetUnreadSmsEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("usageLimitHitEnabled", m.GetUsageLimitHitEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UserNotificationPreferences) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAutomationFailedEnabled sets the automationFailedEnabled property value. Whether automation failed notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetAutomationFailedEnabled(value *bool)() {
    m.automationFailedEnabled = value
}
// SetBillingEmailEnabled sets the billingEmailEnabled property value. Whether billing email is enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetBillingEmailEnabled(value *bool)() {
    m.billingEmailEnabled = value
}
// SetBillingSmsEnabled sets the billingSmsEnabled property value. Whether billing SMS is enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetBillingSmsEnabled(value *bool)() {
    m.billingSmsEnabled = value
}
// SetLowWalletBalanceEnabled sets the lowWalletBalanceEnabled property value. Whether low wallet balance notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetLowWalletBalanceEnabled(value *bool)() {
    m.lowWalletBalanceEnabled = value
}
// SetMissedCallEnabled sets the missedCallEnabled property value. Whether missed call notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetMissedCallEnabled(value *bool)() {
    m.missedCallEnabled = value
}
// SetNewLeadEmailEnabled sets the newLeadEmailEnabled property value. Whether new lead email is enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetNewLeadEmailEnabled(value *bool)() {
    m.newLeadEmailEnabled = value
}
// SetNewLeadEnabled sets the newLeadEnabled property value. Whether new lead notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetNewLeadEnabled(value *bool)() {
    m.newLeadEnabled = value
}
// SetNewLeadSmsEnabled sets the newLeadSmsEnabled property value. Whether new lead SMS is enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetNewLeadSmsEnabled(value *bool)() {
    m.newLeadSmsEnabled = value
}
// SetPaymentFailedEnabled sets the paymentFailedEnabled property value. Whether payment failed notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetPaymentFailedEnabled(value *bool)() {
    m.paymentFailedEnabled = value
}
// SetSubscriptionRenewingEnabled sets the subscriptionRenewingEnabled property value. Whether subscription renewing notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetSubscriptionRenewingEnabled(value *bool)() {
    m.subscriptionRenewingEnabled = value
}
// SetTenDlcStatusEnabled sets the tenDlcStatusEnabled property value. Whether 10DLC status notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetTenDlcStatusEnabled(value *bool)() {
    m.tenDlcStatusEnabled = value
}
// SetUnreadSmsEnabled sets the unreadSmsEnabled property value. Whether unread SMS notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetUnreadSmsEnabled(value *bool)() {
    m.unreadSmsEnabled = value
}
// SetUsageLimitHitEnabled sets the usageLimitHitEnabled property value. Whether usage limit hit notifications are enabled for this user notification preferences.
func (m *UserNotificationPreferences) SetUsageLimitHitEnabled(value *bool)() {
    m.usageLimitHitEnabled = value
}
type UserNotificationPreferencesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutomationFailedEnabled()(*bool)
    GetBillingEmailEnabled()(*bool)
    GetBillingSmsEnabled()(*bool)
    GetLowWalletBalanceEnabled()(*bool)
    GetMissedCallEnabled()(*bool)
    GetNewLeadEmailEnabled()(*bool)
    GetNewLeadEnabled()(*bool)
    GetNewLeadSmsEnabled()(*bool)
    GetPaymentFailedEnabled()(*bool)
    GetSubscriptionRenewingEnabled()(*bool)
    GetTenDlcStatusEnabled()(*bool)
    GetUnreadSmsEnabled()(*bool)
    GetUsageLimitHitEnabled()(*bool)
    SetAutomationFailedEnabled(value *bool)()
    SetBillingEmailEnabled(value *bool)()
    SetBillingSmsEnabled(value *bool)()
    SetLowWalletBalanceEnabled(value *bool)()
    SetMissedCallEnabled(value *bool)()
    SetNewLeadEmailEnabled(value *bool)()
    SetNewLeadEnabled(value *bool)()
    SetNewLeadSmsEnabled(value *bool)()
    SetPaymentFailedEnabled(value *bool)()
    SetSubscriptionRenewingEnabled(value *bool)()
    SetTenDlcStatusEnabled(value *bool)()
    SetUnreadSmsEnabled(value *bool)()
    SetUsageLimitHitEnabled(value *bool)()
}
