// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// UserNotificationPreferences_smsConsentCertificate describes Leadping Consent certificate data used in Leadping API requests and responses.
type UserNotificationPreferences_smsConsentCertificate struct {
	LeadpingConsentCertificate
}

// NewUserNotificationPreferences_smsConsentCertificate instantiates a new UserNotificationPreferences_smsConsentCertificate and sets the default values.
func NewUserNotificationPreferences_smsConsentCertificate() *UserNotificationPreferences_smsConsentCertificate {
	m := &UserNotificationPreferences_smsConsentCertificate{
		LeadpingConsentCertificate: *NewLeadpingConsentCertificate(),
	}
	return m
}

// CreateUserNotificationPreferences_smsConsentCertificateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserNotificationPreferences_smsConsentCertificateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewUserNotificationPreferences_smsConsentCertificate(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *UserNotificationPreferences_smsConsentCertificate) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.LeadpingConsentCertificate.GetFieldDeserializers()
	return res
}

// Serialize serializes information the current object
func (m *UserNotificationPreferences_smsConsentCertificate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.LeadpingConsentCertificate.Serialize(writer)
	if err != nil {
		return err
	}
	return nil
}

type UserNotificationPreferences_smsConsentCertificateable interface {
	LeadpingConsentCertificateable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
